(function(){
const {adm,uni}=UD;const {major,job,store}=EX;const A=SEN_AUTH;const $=id=>document.getElementById(id);
const LS=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))||d;}catch(e){return d;}};
const K='sen-my-v1';let P=LS(K,{parent:'none',teacher:{t1:{test:true,saved:true,grades:false,plan:true,counsel:false}},ai:{save:true,useTest:true,useGrades:true,useSaved:true},alerts:{push:true,sms:false,parent:false,days:3},grade:'고2',school:'서울한빛고',done:{}});const save=()=>localStorage.setItem(K,JSON.stringify(P));
const D=()=>({ex:LS('sen-explore-v1',{jobs:[],majors:[]}),un:LS('sen-univ-v1',{saved:[],adms:[],cmpA:[]}),sc:LS('sen-school-v1',{saved:[]}),pl:LS('sen-plan-v1',null),st:LS('sen-strategy-v1',null),co:LS('sen-counsel-v1',{booking:null,tasks:{},apps:[]}),lib:LS('sen-lib-v1',{scrap:[],applied:[]}),nw:LS('sen-news-v1',{my:[]}),tests:LS('sen-trait-done',[])});
const GROUP={stage:'d',month:'d',next:'d',jobs:'g',schools:'g',unis:'g',tests:'r',plan:'r',records:'r',cal:'a',deadline:'a',counsel:'a',parent:'s',teacher:'s',privacy:'s'};
const L3={stage:'현재 단계',month:'이번 달 할 일',next:'다음 추천 행동',jobs:'관심 직업·학과',schools:'관심 고교',unis:'관심 대학·전형',tests:'진로검사·활동',plan:'학업설계',records:'성적·상담·지원기록',cal:'나의 진로진학 일정',deadline:'마감 알림',counsel:'상담 일정',parent:'학부모 연결',teacher:'교사 공유',privacy:'개인정보·AI 설정'};
const L2={d:'나의 대시보드',g:'나의 목표·관심',r:'나의 계획·기록',a:'일정·알림',s:'공유·권한'};
/* ── 여정 단계 ── */
const STAGES=[['중1·2','나를 알아가기','진로검사 · 직업 탐색'],['중3','고교 선택','고교 유형 · 고입 일정'],['고1','과목 설계 시작','선택과목 · 학과 탐색'],['고2','진로 구체화','학업설계 · 전형 이해 · 관심 대학'],['고3','지원 전략','성적 정리 · 지원계획 · 상담'],['졸업','다음 걸음','정시 · 재도전 · 진로 이어가기']];
const curStage=()=>({'중1':0,'중2':0,'중3':1,'고1':2,'고2':3,'고3':4,'졸업생':5}[P.grade]??3);
function stageTasks(d){const g=curStage();const T={
 3:[['진로검사 3종 완료',d.tests.length>=3||true,'jinro-trait.html'],['관심 직업·학과 저장',d.ex.jobs.length+d.ex.majors.length>0,'jinro-job.html#find'],['2·3학년 과목 계획 세우기',!!(d.pl&&Object.values(d.pl.sem).flat().length),'study-plan.html#sim'],['수시·정시 전형 이해하기',d.un.adms.length>0,'univ.html#susi'],['관심 대학 저장',d.un.saved.length>0,'univ.html#find'],['성적 입력·저장',!!(d.st&&d.st.savedAt),'strategy.html#grades'],['진로·진학 상담 1회',true,'counsel.html#result']],
 4:[['성적 입력·저장',!!(d.st&&d.st.savedAt),'strategy.html#grades'],['관심 전형 비교',d.un.adms.length>=3,'strategy.html#cmp'],['지원계획 작성',!!(d.st&&d.st.plan&&d.st.plan.susi.length),'strategy.html#plan'],['지원전략 상담',!!(d.co.booking),'counsel.html#book'],['면접 준비',false,'strategy.html#interview']]};
 return T[g]||[['진로검사 하기',d.tests.length>0,'jinro-test.html'],['관심 직업 저장',d.ex.jobs.length>0,'jinro-job.html#find'],['고교 유형 알아보기',false,'school-explore.html#types']];}
function renderStage(){const d=D(),g=curStage(),T=stageTasks(d),done=T.filter(t=>t[1]).length;
  $('stageBody').innerHTML=`<div class="journey">${STAGES.map((s,i)=>`<div class="jst${i<g?' is-past':''}${i===g?' is-cur':''}"><i>${i<g?'✓':i+1}</i><b>${s[0]}</b><span>${s[1]}</span></div>`).join('')}</div>
  <div class="ud" style="margin-top:24px"><div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><div class="panel-c__head"><div><small style="color:var(--brand);font-weight:800">지금 단계 · ${STAGES[g][0]}</small><h3 style="font-size:22px">${STAGES[g][1]}</h3></div><div class="ring" style="--p:${Math.round(done/T.length*100)};width:84px;height:84px"><b style="font-size:18px">${done}<small>/${T.length}</small></b></div></div><p style="margin:0;color:var(--ink-2)">${STAGES[g][2]}를 중심으로 움직이는 시기예요. 아래 할 일을 하나씩 끝내면 다음 단계 준비가 돼요.</p><div class="reclist">${T.map(t=>`<a class="cbx${t[1]?' is-on':''}" style="min-width:0;justify-content:space-between;text-decoration:none" href="${t[2]}"><span style="display:flex;gap:8px;align-items:center"><input type="checkbox" disabled${t[1]?' checked':''}><span${t[1]?' style="color:var(--ink-3)"':''}>${t[0]}</span></span><span class="link" style="font-size:13px">${t[1]?'보기':'하러 가기'} ›</span></a>`).join('')}</div></div>
  <div><div class="panel-c" style="background:var(--surface);box-shadow:none"><h3>다음 단계 미리보기 · ${STAGES[Math.min(g+1,5)][0]}</h3><p style="margin:0;color:var(--ink-2)">${STAGES[Math.min(g+1,5)][2]}</p><p class="hint" style="margin:0">학년이 바뀌면 단계와 할 일이 자동으로 바뀌어요. 학년 정보는 <a class="link" href="#privacy">개인정보 설정</a>에서 고칩니다.</p></div><div class="panel-c" style="margin-top:16px;border:1px solid var(--line);box-shadow:none"><h3>내가 쌓은 것</h3><div class="kv3" style="grid-template-columns:1fr 1fr"><div><b>${d.tests.length||3}</b><span>완료한 검사</span></div><div><b>${d.ex.jobs.length+d.ex.majors.length}</b><span>관심 직업·학과</span></div><div><b>${d.un.saved.length+d.un.adms.length}</b><span>관심 대학·전형</span></div><div><b>${2+(d.co.booking?1:0)}</b><span>상담 (예정 포함)</span></div></div></div></div></div>`;}
/* ── 이번 달 할 일 / 추천 행동 ── */
function monthItems(d){const it=[];
  if(d.co.booking&&d.co.booking.date)it.push({d:'10.'+d.co.booking.date.slice(3,5),t:`${d.co.booking.type==='visit'?'센터 방문':d.co.booking.type==='video'?'화상':'학교'} 상담 ${d.co.booking.slot}`,k:'상담',h:'counsel.html#book'});
  d.co.apps.forEach(id=>{const X={x1:['10.18','UX 디자이너 앱 화면 설계 체험'],x2:['10.25','생명과학 연구실 하루 체험'],x3:['11.01','통계 분석 워크숍']}[id];if(X&&X[0].startsWith('10'))it.push({d:X[0],t:X[1],k:'체험',h:'counsel.html#apply'});});
  if(d.lib.applied.includes('e1'))it.push({d:'10.08',t:'수시 면접 대비 설명회 19:00',k:'설명회',h:'library.html#briefing'});if(d.lib.applied.includes('e3'))it.push({d:'10.22',t:'고1 과목 선택 설명회 19:00',k:'설명회',h:'library.html#briefing'});
  d.nw.my.forEach(k=>{const m=k.match(/^2026-10-(\d\d)(.*)$/);if(m)it.push({d:'10.'+m[1],t:m[2],k:'일정',h:'news.html#schedule'});});
  it.push({d:'10.30',t:'2학년 2학기 선택과목 수강 신청 (학교별)',k:'마감',h:'study-plan.html#sim'});
  Object.entries({t1:'디자인 계열 진로체험 1개 신청하기',t2:'과목 선택 시뮬레이션에 미적분Ⅰ·확률과 통계 담기',t3:'UX 디자이너 직업인 인터뷰 영상 보기'}).forEach(([k,t])=>{if(!d.co.tasks[k])it.push({d:'10월 중',t,k:'후속 과제',h:'counsel.html#result',task:k});});
  return it.sort((a,b)=>a.d.localeCompare(b.d));}
function renderMonth(){const d=D(),it=monthItems(d),today='10.02';
  $('monthBody').innerHTML=`<div class="rbar" style="margin-top:0"><div><h3 style="margin:0;font-size:22px">2026년 10월 · ${it.length}개</h3><p class="section__sub" style="font-size:14px">상담, 체험, 설명회, 마감, 후속 과제를 한곳에 모았어요</p></div><div class="fchips">${['전체','상담','체험','설명회','마감','후속 과제'].map(k=>`<button class="fchip${(P.mf||'전체')===k?' is-on':''}" data-mf="${k}">${k}</button>`).join('')}</div></div>
  <ul class="ups" style="margin-top:18px">${it.filter(x=>!P.mf||P.mf==='전체'||x.k===P.mf).map(x=>{const past=/^\d\d\.\d\d$/.test(x.d)&&x.d<today;return `<li class="up${past?' is-past':''}"><div class="up__d"><b>${x.d}</b><span>${past?'지남':x.d===today?'오늘':/^\d\d\.\d\d$/.test(x.d)?'D-'+(parseInt(x.d.slice(3))-2):''}</span></div><div class="up__m"><span class="tb tb--${{'상담':2,'체험':3,'설명회':1,'마감':0,'일정':1,'후속 과제':2}[x.k]}">${x.k}</span><b>${x.t}</b></div>${x.task?`<label class="cbx" style="min-width:0"><input type="checkbox" data-mtask="${x.task}"><span style="font-size:13px">완료</span></label>`:`<a class="mini" href="${x.h}" style="flex:none">보기 ›</a>`}</li>`;}).join('')||'<li class="hint">이 종류의 일정이 없어요</li>'}</ul>`;}
function nextActions(d){const out=[];
  if(!(d.st&&d.st.savedAt))out.push(['성적을 입력하고 저장해요','교과군 평균 등급만 고르면 돼요. 저장해야 분석과 상담 사전자료에 반영됩니다','strategy.html#grades','5분']);
  if(d.ex.majors.length<3)out.push(['관심 학과를 3개 이상 저장해요','학과가 있어야 대학·전형 추천과 과목 계획이 이어져요','jinro-major.html#find','10분']);
  if(d.un.adms.length<3)out.push(['관심 전형을 저장해 비교해요','수시·정시 전형 요건을 나란히 보면 지원계획이 쉬워져요','univ.html#susi','15분']);
  if(!(d.pl&&Object.values(d.pl.sem).flat().length>=8))out.push(['2·3학년 과목 계획을 채워요','10월 말 수강 신청 전에 목표 학과 추천 과목으로 채워보세요','study-plan.html#sim','15분']);
  if(!d.co.booking)out.push(['다음 상담을 예약해요','9월 모의고사 결과를 반영해 참고 범위를 다시 볼 때예요','counsel.html#book','3분']);
  const t=Object.entries({t1:'디자인 계열 진로체험 신청',t2:'미적분Ⅰ·확률과 통계 담기',t3:'UX 디자이너 인터뷰 영상'}).filter(([k])=>!d.co.tasks[k]);if(t.length)out.push([`상담 후속 과제 ${t.length}개를 끝내요`,t.map(x=>x[1]).join(' · '),'counsel.html#result','']);
  if(!out.length)out.push(['지금 할 일을 다 했어요','학기 중에는 세특에 남을 수업 활동에 집중하고, 변화가 생기면 검사·관심을 업데이트하세요','jinro-change.html','']);
  return out.slice(0,4);}
function renderNext(){const d=D(),N=nextActions(d);
  $('nextBody').innerHTML=`<div class="nxgrid">${N.map((n,i)=>`<a class="nx${i?'':' is-1'}" href="${n[2]}"><small>${i?'그다음':'지금 바로'}${n[3]?' · '+n[3]:''}</small><b>${n[0]}</b><p>${n[1]}</p><span class="link">하러 가기 ›</span></a>`).join('')}</div>
  <div class="notice" style="margin-top:20px"><div class="notice__icon">💡</div><div><h3>추천은 어떻게 정해지나요?</h3><p>내 학년(${P.grade})과 지금까지 저장한 것(검사·관심·성적·계획·상담)을 보고 빠진 순서대로 골라요. 사람의 판단이 들어간 추천이 아니라 '아직 안 한 것' 안내이니, 순서는 상담에서 선생님과 바꿔도 됩니다.</p></div></div>`;}
/* ── 관심 ── */
function renderJobs(){const d=D();const J=d.ex.jobs.map(job).filter(Boolean),M=d.ex.majors.map(major).filter(Boolean);
  $('jobsBody').innerHTML=`<div class="ud"><div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><div class="panel-c__head"><h3>관심 직업 <span style="color:var(--brand)">${J.length}</span></h3><a class="link" href="jinro-job.html#find">더 찾기 ›</a></div>${J.length?`<div class="alist">${J.map(j=>`<div class="arow" style="cursor:default"><span class="tb tb--1">${j.cat}</span><div><b>${j.name}</b><span>${j.ria.map(k=>EX.RIASEC[k]).join('·')} · ${j.majors.map(m=>major(m).name).join(', ')}</span></div><a class="mini" href="jinro-job.html?open=${j.id}#find" style="flex:none">상세</a><button class="save is-on" data-rm="jobs:${j.id}" aria-label="빼기">❤️</button></div>`).join('')}</div>`:'<p class="hint" style="margin:0">아직 없어요. 직업 찾기에서 🤍를 눌러 저장하세요.</p>'}</div>
  <div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><div class="panel-c__head"><h3>관심 학과 <span style="color:var(--brand)">${M.length}</span></h3><a class="link" href="jinro-major.html#find">더 찾기 ›</a></div>${M.length?`<div class="alist">${M.map(m=>`<div class="arow" style="cursor:default"><span class="tb tb--2">${m.cat}</span><div><b>${m.name}</b><span>개설 대학 ${UD.UNIS.filter(u=>u.majors.includes(m.id)).length}곳 · 고교 과목 ${m.subjects.slice(0,2).join(', ')}</span></div><a class="mini" href="univ.html#majorinfo" style="flex:none">대학 보기</a><button class="save is-on" data-rm="majors:${m.id}" aria-label="빼기">❤️</button></div>`).join('')}</div>`:'<p class="hint" style="margin:0">아직 없어요. 학과 찾기에서 🤍를 눌러 저장하세요.</p>'}</div></div>
  <p class="hint">관심 목록은 직업·학과 탐색, 과목 계획, 대학·전형 추천, 상담 사전자료에 함께 쓰여요. 중복 저장은 자동으로 하나로 합쳐집니다.</p>`;}
function renderSchools(){const d=D(),S=d.sc.saved.map(id=>SC.SCHOOLS.find(s=>s.id===id)).filter(Boolean);
  $('schoolsBody').innerHTML=`<div class="rbar" style="margin-top:0"><div><h3 style="margin:0;font-size:20px">관심 고교 <span style="color:var(--brand)">${S.length}</span></h3><p class="section__sub" style="font-size:14px">${P.grade.startsWith('중')?'고입을 앞두고 비교해 둔 학교예요':'고등학생이 되면 이 목록은 참고 기록으로 남아요'}</p></div><a class="link" href="school-explore.html#schools">학교 찾기·비교 ›</a></div>${S.length?`<div class="cards" style="margin-top:16px">${S.map(s=>`<article class="xcard" style="cursor:default"><div class="xcard__top"><div><span class="xcard__cat">${s.gu} · ${SC.TNAME[s.type]} · ${s.coed}</span><h3>${s.name}</h3></div><button class="save is-on" data-rm="school:${s.id}">❤️</button></div><div class="ria">${s.feats.map(x=>`<span>${x}</span>`).join('')}</div><div class="ind"><div>개설 과목 <b style="color:var(--ink)">${s.subj}개</b></div><div>통학 <b style="color:var(--ink)">${s.commute}분</b></div></div></article>`).join('')}</div>`:'<div class="empty-r" style="margin-top:16px"><b>저장한 고교가 없어요</b>학교 찾기·비교에서 🤍를 눌러 저장하세요.</div>'}`;}
function renderUnis(){const d=D(),U=d.un.saved.map(uni).filter(Boolean),Ad=d.un.adms.map(adm).filter(Boolean),plan=d.st&&d.st.plan;
  $('unisBody').innerHTML=`<div class="ud"><div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><div class="panel-c__head"><h3>관심 대학 <span style="color:var(--brand)">${U.length}</span></h3><a class="link" href="univ.html#find">더 찾기 ›</a></div>${U.length?`<div class="alist">${U.map(u=>`<div class="arow" style="cursor:default"><span class="tb tb--1">${u.region}</span><div><b>${u.name}</b><span>${u.type} · ${u.size} · 내 관심 학과 ${u.majors.filter(m=>d.ex.majors.includes(m)).length}개</span></div><a class="mini" href="univ.html?uni=${u.id}#detail" style="flex:none">상세</a><button class="save is-on" data-rm="uni:${u.id}">❤️</button></div>`).join('')}</div>`:'<p class="hint" style="margin:0">아직 없어요.</p>'}</div>
  <div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><div class="panel-c__head"><h3>관심 전형 <span style="color:var(--brand)">${Ad.length}</span></h3><a class="link" href="strategy.html#cmp">비교하기 ›</a></div>${Ad.length?`<div class="alist">${Ad.map(a=>{const inPlan=plan&&(plan.susi.includes(a.id)||Object.values(plan.jeongsi).includes(a.id));return `<div class="arow" style="cursor:default"><span class="tb tb--${a.season==='수시'?1:2}">${a.season}</span><div><b>${uni(a.uni).name} · ${a.name}</b><span>${a.kind} · ${a.minType==='반영안함'?'최저 없음':'최저 있음'}${a.docs.includes('면접')?' · 면접':''}${inPlan?' · <b style="color:#0E8A57">지원계획에 담김</b>':''}</span></div><button class="save is-on" data-rm="adm:${a.id}">❤️</button></div>`;}).join('')}</div>`:'<p class="hint" style="margin:0">아직 없어요. <a class="link" href="univ.html#susi">전형 찾기 ›</a></p>'}</div></div>`;}
/* ── 계획·기록 ── */
function renderTests(){const d=D();
  $('testsBody').innerHTML=`<div class="ud"><div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><div class="panel-c__head"><h3>진로검사 기록</h3><a class="link" href="jinro-trait.html">나의 진로특성 ›</a></div><div class="ctable-w"><table class="ctable utbl"><thead><tr><th>검사</th><th>검사일</th><th>결과 요약</th></tr></thead><tbody>${[['직업흥미검사(H)','2026.09.28','탐구형 + 예술형 (IA)'],['직업적성검사','2026.05.14','수리·논리력 · 공간지각력 · 창의력'],['직업가치관검사','2026.03.20','지식추구 · 자율성 · 사회공헌'],['직업흥미검사(H)','2025.10.15','탐구형 + 현실형 (IR)']].map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('')}</tbody></table></div><a class="link" href="jinro-change.html">검사·관심 변화보기 ›</a></div>
  <div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><div class="panel-c__head"><h3>활동 기록</h3><small>체험·설명회·영상</small></div><ul class="reading">${[d.co.apps.length?['진로체험 신청 '+d.co.apps.length+'건','counsel.html#apply']:null,d.lib.applied.length?['진학설명회 신청 '+d.lib.applied.length+'건','library.html#briefing']:null,d.lib.scrap.length?['자료 스크랩 '+d.lib.scrap.length+'건','library.html#hs12']:null,['2026.09.30 센터 방문 상담 · 디자인 계열 체험 권유','counsel.html#result'],['2026.06.12 진로 영상 시청 후 과학 커뮤니케이터 저장','library.html#video']].filter(Boolean).map(x=>`<li><b>${x[0]}</b><a class="link" href="${x[1]}" style="font-size:13px">보기 ›</a></li>`).join('')}</ul><p class="hint" style="margin:0">학교생활기록부와는 별개인 '내 기록'이에요. 상담 사전자료로만 쓰이고 대학에 전달되지 않습니다.</p></div></div>`;}
function renderPlan(){const d=D(),pl=d.pl;
  $('planBody').innerHTML=pl&&Object.values(pl.sem).flat().length?`<div class="rbar" style="margin-top:0"><div><h3 style="margin:0;font-size:20px">목표 학과 · ${major(pl.major)?major(pl.major).name:'–'}</h3><p class="section__sub" style="font-size:14px">선택과목 ${Object.values(pl.sem).flat().length}과목 · ${pl.submit===3?'선생님 답장 도착':pl.submit>0?'선생님 확인 중':'작성 중'}</p></div><a class="btn btn--ghost btn--pill" href="study-plan.html#sim">계획 고치기</a></div><div class="road" style="margin-top:16px">${SC.SEMS.map(k=>`<div class="road__c"><b>${SC.SEM_LABEL[k]}</b>${(pl.sem[k]||[]).map(n=>`<span>${n}</span>`).join('')||'<em>비어 있음</em>'}</div>`).join('')}</div><div class="ud" style="margin-top:20px"><div class="panel-c" style="background:var(--surface);box-shadow:none"><h3>이 계획과 이어지는 것</h3><ul class="reading"><li><b>관심 학과</b>${d.ex.majors.map(m=>major(m)?.name).filter(Boolean).join(', ')||'–'}</li><li><b>우리 학교 미개설 과목</b>${Object.values(pl.sem).flat().filter(x=>SC.NOT_OFFERED.includes(x)).join(', ')||'없음'} → 공동교육과정·온라인학교</li></ul></div><div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><h3>점검·상담</h3><p style="margin:0;color:var(--ink-2);font-size:14.5px">함께 살펴볼 점을 정리해 선생님께 보내고 상담에서 최종 계획을 정해요.</p><a class="btn btn--primary btn--pill" href="study-plan.html#check" style="align-self:flex-start">계획 점검 →</a></div></div>`:`<div class="empty-r"><b>아직 과목 계획이 없어요</b>목표 학과를 고르면 추천 과목으로 바로 채울 수 있어요.<div style="margin-top:12px"><a class="btn btn--primary btn--pill" href="study-plan.html#sim">과목 선택 시뮬레이션 →</a></div></div>`;}
function renderRecords(){const d=D(),st=d.st;const avg=o=>{const v=Object.values(o||{}).filter(Boolean);return v.length?(v.reduce((a,b)=>a+b,0)/v.length).toFixed(1):'–';};
  $('recordsBody').innerHTML=`<div class="kv3" style="grid-template-columns:repeat(4,minmax(0,1fr))"><div><b>${st&&st.savedAt?avg(Object.assign({},...Object.values(st.grades).map(g=>g))):'–'}</b><span>내신 평균 (저장본)</span></div><div><b>${st?avg(st.mock['2026-09']):'–'}</b><span>9월 모의고사 평균</span></div><div><b>${2+(d.co.booking?1:0)}</b><span>상담 횟수</span></div><div><b>${st&&st.plan?st.plan.susi.length+'/6':'0/6'}</b><span>수시 지원계획</span></div></div>
  <div class="ud" style="margin-top:20px"><div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><div class="panel-c__head"><h3>성적 기록</h3><a class="link" href="strategy.html#grades">입력·수정 ›</a></div>${st&&st.savedAt?`<p style="margin:0;color:var(--ink-2);font-size:14.5px">마지막 저장 ${st.savedAt}. 교과군 평균 등급과 모의고사 영역 등급만 저장되어 있어요.</p><a class="link" href="strategy.html#analysis">성적·기록 분석 ›</a>`:'<p class="hint" style="margin:0">저장한 성적이 없어요.</p>'}</div>
  <div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><div class="panel-c__head"><h3>상담 기록</h3><a class="link" href="counsel.html#result">결과·후속과제 ›</a></div><ul class="reading"><li><b>2026.09.30 센터 방문 상담</b>흥미 변화 확인 · 디자인 계열 체험 권유 · 후속 과제 3개</li><li><b>2026.05.20 담임 선생님 상담</b>1학년 성적 흐름 점검 · 진로검사 재실시</li>${d.co.booking?`<li><b>${d.co.booking.type==='board'?'게시판 질문 등록 · 답변 대기':d.co.booking.date+' '+d.co.booking.slot+' 예약됨'}</b>${d.co.booking.topics.join(', ')||'주제 미정'}</li>`:''}</ul></div></div>
  <div class="panel-c" style="margin-top:20px;border:1px solid var(--line);box-shadow:none"><div class="panel-c__head"><h3>지원 기록</h3><a class="link" href="strategy.html#plan">지원계획 ›</a></div>${st&&st.plan&&(st.plan.susi.length||Object.values(st.plan.jeongsi).some(Boolean))?`<div class="lchips">${st.plan.susi.map(id=>adm(id)).filter(Boolean).map(a=>`<span>수시 · ${uni(a.uni).name} ${a.name}</span>`).join('')}${Object.entries(st.plan.jeongsi).filter(([g,id])=>id).map(([g,id])=>{const a=adm(id);return `<span>정시 ${g} · ${uni(a.uni).name}</span>`;}).join('')}</div><p class="hint" style="margin:8px 0 0">실제 원서 접수 결과(접수·합격·등록)는 고3 원서 접수 후 이곳에 기록돼요.</p>`:'<p class="hint" style="margin:0">아직 지원계획이 없어요. 고3이 되기 전에는 관심 전형 비교로 준비해요.</p>'}</div>`;}
/* ── 일정·알림 ── */
function renderCal(){const d=D(),it=monthItems(d).filter(x=>/^\d\d\.\d\d$/.test(x.d));const days=new Date(2026,10,0).getDate(),first=new Date(2026,9,1).getDay();
  $('calBody').innerHTML=`<div class="calw"><div class="calbox"><div class="calhd"><span></span><b>2026년 10월</b><span></span></div><div class="cdw"><span>일</span><span>월</span><span>화</span><span>수</span><span>목</span><span>금</span><span>토</span></div><div class="cal">${'<div></div>'.repeat(first)}${Array.from({length:days},(_,i)=>{const dd=String(i+1).padStart(2,'0'),E=it.filter(x=>x.d==='10.'+dd);return `<div class="cd${i+1===2?' is-today':''}${E.length?' has':''}"><b>${i+1}</b>${E.map(e=>`<i class="dot dot--${{'상담':'a','체험':'c','설명회':'b','마감':'a','일정':'b'}[e.k]||'b'}"></i>`).join('')}</div>`;}).join('')}</div><div class="calleg"><span><i class="dot dot--a"></i> 상담·마감</span><span><i class="dot dot--b"></i> 설명회·일정</span><span><i class="dot dot--c"></i> 체험</span></div></div>
  <div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><h3>이번 달 일정</h3><ul class="ups">${it.map(x=>`<li class="up"><div class="up__d"><b>${x.d}</b></div><div class="up__m"><span class="tb tb--1">${x.k}</span><b>${x.t}</b></div><a class="mini" href="${x.h}" style="flex:none">›</a></li>`).join('')||'<li class="hint">일정이 없어요</li>'}</ul><p class="hint" style="margin:0">입시 공식 일정은 <a class="link" href="news.html#schedule">일정·소식</a>에서 '내 일정'으로 추가하면 여기에 함께 보여요.</p></div></div>`;}
function renderDeadline(){const d=D();const DL=[['10.30','2학년 2학기 선택과목 수강 신청','학교','study-plan.html#sim'],['10.17','UX 디자이너 체험 신청 마감','체험','counsel.html#exp'],['11.04','2028 대입 개편 학부모 설명회 접수 마감','설명회','library.html#briefing'],['12.10','후기고 원서 접수 (중3)','고입','school-explore.html#admission']];
  $('deadlineBody').innerHTML=`<div class="ud"><div><h3 style="margin:0 0 12px;font-size:20px">다가오는 마감</h3><ul class="ups">${DL.map(x=>`<li class="up"><div class="up__d"><b>${x[0]}</b><span>D-${Math.max(0,Math.round((new Date('2026-'+x[0].replace('.','-'))-new Date('2026-10-02'))/864e5))}</span></div><div class="up__m"><span class="tb tb--2">${x[2]}</span><b>${x[1]}</b></div><a class="mini" href="${x[3]}" style="flex:none">›</a></li>`).join('')}</ul></div>
  <div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><h3>알림 설정</h3><div class="reclist">${[['push','앱·웹 알림',true],['sms','문자(SMS) 알림',false],['parent','보호자에게도 함께 알림 (학부모 연결 시)',false]].map(([k,n])=>`<label class="cbx${P.alerts[k]?' is-on':''}" style="min-width:0"><input type="checkbox" data-al="${k}"${P.alerts[k]?' checked':''}${k==='parent'&&P.parent!=='linked'?' disabled':''}><span>${n}${k==='parent'&&P.parent!=='linked'?' <small style="color:var(--ink-3)">· 연결 후 가능</small>':''}</span></label>`).join('')}</div><label class="fld">며칠 전에 알릴까요?<select class="sortsel" id="alDays">${[1,3,7].map(n=>`<option value="${n}"${P.alerts.days===n?' selected':''}>${n}일 전</option>`).join('')}</select></label><p class="hint" style="margin:0">상담·체험·설명회는 신청하면 자동으로 알림 대상이 돼요.</p></div></div>`;}
function renderCounsel(){const d=D(),b=d.co.booking;const TN={teacher:'학교 선생님 상담',visit:'센터 방문 상담',video:'화상 상담',board:'온라인 상담'};
  $('counselBody').innerHTML=`<div class="ud"><div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><h3>예정된 상담</h3>${b?`<div class="arow" style="cursor:default"><span class="tb tb--1">예약</span><div><b>${TN[b.type]}</b><span>${b.type==='board'?'2~3일 내 답변 예정':b.date+' '+b.slot}${b.parent?' · 보호자 동반':''} · 주제: ${b.topics.join(', ')||'미정'}</span></div><a class="mini" href="counsel.html#book" style="flex:none">자세히</a></div><p class="hint" style="margin:8px 0 0">사전자료 ${Object.values(b.share).filter(Boolean).length}개 항목이 전달될 예정이에요. 공유 범위는 예약 화면에서 바꿀 수 있어요.</p>`:'<p class="hint" style="margin:0">예정된 상담이 없어요.</p><a class="btn btn--primary btn--pill" href="counsel.html#book" style="align-self:flex-start">상담 예약 →</a>'}</div>
  <div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><h3>지난 상담</h3><ul class="reading"><li><b>2026.09.30 · 센터 방문 · 이진로 선생님</b>후속 과제 ${3-Object.values(d.co.tasks).filter(Boolean).length+2}개 남음 <a class="link" href="counsel.html#result" style="font-size:13px">보기 ›</a></li><li><b>2026.05.20 · 학교 · 담임 선생님</b>완료</li></ul></div></div>`;}
/* ── 공유·권한 ── */
function renderParent(){const st=P.parent;
  $('parentBody').innerHTML=st==='linked'?`<div class="uhead" style="align-items:center"><div><small>연결됨 · 2026.10.02</small><h2 style="font-size:22px">보호자 1명이 연결되어 있어요</h2><p style="margin:0;color:var(--ink-2)">김보호 님 (어머니) · 학부모 계정</p></div><button class="btn btn--ghost btn--pill" data-parent="none">연결 해제</button></div>
    <div class="ud" style="margin-top:20px"><div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><h3>보호자가 볼 수 있는 것</h3><p style="margin:0;color:var(--ink-2);font-size:14.5px">내가 허락한 항목만 보여요. 언제든 바꿀 수 있어요.</p><div class="reclist">${[['pTest','진로검사 결과'],['pSaved','관심 직업·학과·대학·전형'],['pGrades','내가 입력한 성적'],['pPlan','과목 계획·지원계획'],['pCounsel','상담 일정 (내용은 제외)'],['pCal','일정·알림']].map(([k,n])=>`<label class="cbx${P[k]!==false?' is-on':''}" style="min-width:0"><input type="checkbox" data-pshare="${k}"${P[k]!==false?' checked':''}><span>${n}</span></label>`).join('')}</div></div>
    <div class="panel-c" style="background:var(--surface);box-shadow:none"><h3>보호자가 할 수 있는 것</h3><ul class="reading"><li><b>함께 상담 예약</b>보호자 동반 상담을 신청할 수 있어요</li><li><b>설명회 신청</b>학부모 대상 설명회를 신청할 수 있어요</li><li><b>볼 수 없는 것</b>상담 내용, AI 대화, 내가 끈 항목</li></ul><p class="hint" style="margin:0">보호자가 잠긴 항목을 열면 "자녀 동의 필요"라고 안내돼요.</p></div></div>`
  :st==='pending'?`<div class="lockbox" style="margin-top:0"><div class="lockbox__ic">⏳</div><div><h3>보호자 승인을 기다리고 있어요</h3><p>연결 코드 <b style="font-size:20px;letter-spacing:.1em">SEN-4827</b> 을 보호자에게 알려주세요. 보호자가 학부모 계정에서 코드를 입력하면 연결돼요. 코드는 24시간 동안 유효합니다.</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn--ghost btn--pill" data-toast="연결 코드를 복사했어요">코드 복사</button><button class="btn btn--primary btn--pill" data-parent="linked">(목업) 보호자 승인 완료</button><button class="link" data-parent="none">취소</button></div></div></div>`
  :`<div class="lockbox" style="margin-top:0"><div class="lockbox__ic">👨‍👩‍👧</div><div><h3>보호자를 연결하면 함께 준비할 수 있어요</h3><p>보호자는 내가 허락한 범위에서만 내 진로진학 정보를 보고, 설명회·상담을 함께 신청할 수 있어요. 연결은 내가 시작하고, 언제든 끊을 수 있습니다. 미성년자의 학생부·성적 자료 제공에는 보호자 동의도 필요해요.</p><button class="btn btn--primary btn--pill" data-parent="pending">연결 코드 만들기</button></div></div>
    <div class="preview" style="margin-top:20px"><div><span class="tb tb--1">1</span><b>연결 코드 만들기</b><span>내 계정에서 코드를 만들어요</span></div><div><span class="tb tb--2">2</span><b>보호자가 코드 입력</b><span>학부모 계정(NEIS 보호자 승인과 연동 예정)</span></div><div><span class="tb tb--3">3</span><b>공유 범위 정하기</b><span>항목별로 보여줄지 내가 정해요</span></div></div>`;}
function renderTeacher(){const T=[['t1','이진로','서울한빛고 · 2학년 진로진학 담당'],['t2','박담임','서울한빛고 · 2학년 3반 담임']];
  $('teacherBody').innerHTML=`<p style="margin:0 0 16px;color:var(--ink-2)">학교 선생님은 NEIS에서 내 학생부와 성적을 봅니다. 여기서는 <b>이 플랫폼에서 내가 만든 것</b>(검사·관심·계획·상담 기록)을 어느 선생님에게 보여줄지 정해요.</p>
  <div class="ud">${T.map(([id,n,d])=>{const s=P.teacher[id]||{};return `<div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><div class="fb__who"><span class="avatar" style="width:44px;height:44px;font-size:16px">${n[0]}</span><div><b>${n} 선생님</b><small>${d}</small></div><span class="st ${Object.values(s).some(Boolean)?'st--ok':'st--done'}" style="margin-left:auto">${Object.values(s).some(Boolean)?'공유 중':'공유 안 함'}</span></div><div class="reclist">${[['test','진로검사 결과'],['saved','관심 직업·학과·대학·전형'],['grades','내가 입력한 성적'],['plan','과목 계획·지원계획'],['counsel','센터 상담 요약']].map(([k,l])=>`<label class="cbx${s[k]?' is-on':''}" style="min-width:0"><input type="checkbox" data-tshare="${id}:${k}"${s[k]?' checked':''}><span>${l}</span></label>`).join('')}</div></div>`;}).join('')}</div>
  <div class="notice" style="margin-top:20px"><div class="notice__icon">🔒</div><div><h3>센터 상담 요약을 학교 선생님과 공유하려면</h3><p>교내 상담 기록과 센터 상담 기록을 연결하는 데에는 내 동의가 필요해요. 선생님 쪽 기록의 '공개 여부'와 내 설정이 모두 허용일 때만 서로 보입니다.</p></div></div>`;}
function renderPrivacy(){
  $('privacyBody').innerHTML=`<div class="ud"><div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><h3>내 정보</h3><label class="fld">학년<select class="sortsel" id="pvGrade">${['중1','중2','중3','고1','고2','고3','졸업생'].map(g=>`<option${P.grade===g?' selected':''}>${g}</option>`).join('')}</select></label><label class="fld">학교<input class="gsel" style="width:100%;text-align:left" id="pvSchool" value="${P.school}"></label><p class="hint" style="margin:0">학년을 바꾸면 현재 단계, 맞춤 자료, 일정이 함께 바뀌어요. 학교는 개설과목 확인에 쓰여요.</p></div>
  <div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><h3>AI 안내 설정</h3><div class="reclist">${[['save','AI 대화 저장하기','끄면 대화가 창을 닫을 때 지워져요'],['useTest','AI가 내 진로검사 결과 사용','"내 정보로 질문하기"에서 참고'],['useGrades','AI가 내가 입력한 성적 사용',''],['useSaved','AI가 내 관심 목록 사용','']].map(([k,n,d])=>`<label class="cbx${P.ai[k]?' is-on':''}" style="min-width:0;align-items:flex-start"><input type="checkbox" data-ai="${k}"${P.ai[k]?' checked':''}><span><b style="display:block">${n}</b>${d?`<small style="color:var(--ink-3)">${d}</small>`:''}</span></label>`).join('')}</div><p class="hint" style="margin:0">AI는 정보 안내만 하고 판정하지 않아요. 내 정보는 이 서비스 안에서만 쓰이고 외부 학습에 쓰이지 않습니다.</p></div></div>
  <div class="ud" style="margin-top:20px"><div class="panel-c" style="background:var(--surface);box-shadow:none"><h3>공유 현황</h3><ul class="reading"><li><b>보호자</b>${P.parent==='linked'?'1명 연결 · 항목별 설정':'연결 안 됨'} <a class="link" href="#parent" style="font-size:13px">설정 ›</a></li><li><b>학교 선생님</b>${Object.values(P.teacher).filter(s=>Object.values(s).some(Boolean)).length}명과 공유 중 <a class="link" href="#teacher" style="font-size:13px">설정 ›</a></li><li><b>센터 상담사</b>상담 예약 시 내가 고른 사전자료만</li></ul></div>
  <div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><h3>내 데이터</h3><div style="display:flex;flex-direction:column;gap:8px"><button class="btn btn--ghost btn--pill" data-toast="내 데이터를 파일로 내려받습니다 (검사·관심·계획·기록)">내 데이터 내려받기</button><button class="btn btn--ghost btn--pill" data-toast="AI 대화 기록을 지웠어요">AI 대화 기록 지우기</button><button class="btn btn--ghost btn--pill" style="color:#C43B3B" data-wipe>이 플랫폼의 내 기록 모두 지우기</button></div><p class="hint" style="margin:0">지우기는 이 플랫폼에 저장된 것만 해당해요. 학교생활기록부·NEIS 자료는 학교가 관리합니다.</p></div></div>`;}
/* ── 탭 ── */
let tab='stage';
const R={stage:renderStage,month:renderMonth,next:renderNext,jobs:renderJobs,schools:renderSchools,unis:renderUnis,tests:renderTests,plan:renderPlan,records:renderRecords,cal:renderCal,deadline:renderDeadline,counsel:renderCounsel,parent:renderParent,teacher:renderTeacher,privacy:renderPrivacy};
function rerender(){const g=GROUP[tab];
  $('ptabs').innerHTML=Object.keys(L3).filter(k=>GROUP[k]===g).map(k=>`<a class="ptab${k===tab?' is-on':''}" href="#${k}">${L3[k]}</a>`).join('');
  $('crumbL2').textContent=L2[g];$('crumbL3').textContent=L3[tab];$('h1').textContent=L2[g];
  $('hdesc').textContent={d:'중학생부터 졸업까지, 내가 저장하고 계획하고 기록한 것이 쌓이는 나만의 공간입니다.',g:'여러 화면에서 저장한 관심 목록을 한곳에서 봅니다. 중복은 자동으로 합쳐져요.',r:'검사, 과목 계획, 성적·상담·지원 기록을 모아 봅니다. 모두 내 기록이며 상담 사전자료로만 쓰여요.',a:'상담·체험·설명회·마감을 한 달력에서 보고 알림을 설정합니다.',s:'누가 내 정보를 볼 수 있는지 내가 정합니다. 잠긴 항목은 상대에게 "동의 필요"로 안내돼요.'}[g];
  const gated=!A.logged();$('gateBox').innerHTML=gated?A.gate('🔒','나의 진로진학은 로그인 후 이용할 수 있어요','내가 저장한 검사·관심·계획·기록이 모이는 개인 공간이라 본인 확인이 필요합니다.'):'';
  document.querySelectorAll('.pane').forEach(p=>p.classList.toggle('is-on',!gated&&p.id==='pane-'+tab));
  if(!gated)R[tab]();}
function setTab(){tab=(location.hash||'#stage').slice(1);if(!L3[tab])tab='stage';document.querySelectorAll('#lnb a').forEach(a=>a.classList.toggle('is-cur',a.getAttribute('href')==='my.html#'+tab));document.title=L3[tab]+' | 서울 진로진학 통합플랫폼';rerender();}
$('lnb').dataset.current=L3[(location.hash||'#stage').slice(1)]||L3.stage;
addEventListener('hashchange',()=>{setTab();scrollTo({top:document.querySelector('.ptabs').offsetTop-90,behavior:'smooth'});});
document.addEventListener('sen-auth',rerender);
document.addEventListener('click',e=>{const c=x=>e.target.closest(x);let b;
  if(b=c('[data-mf]')){P.mf=b.dataset.mf;save();renderMonth();return;}
  if(b=c('[data-rm]')){const [t,id]=b.dataset.rm.split(':');if(t==='jobs'||t==='majors')store.toggleSave(t,id);else{const key={school:'sen-school-v1',uni:'sen-univ-v1',adm:'sen-univ-v1'}[t],s=LS(key,{});if(t==='adm'){s.adms=(s.adms||[]).filter(x=>x!==id);s.cmpA=(s.cmpA||[]).filter(x=>x!==id);}else{s.saved=(s.saved||[]).filter(x=>x!==id);s.cmp=(s.cmp||[]).filter(x=>x!==id);}localStorage.setItem(key,JSON.stringify(s));}showToast('관심 목록에서 뺐어요');rerender();return;}
  if(b=c('[data-parent]')){P.parent=b.dataset.parent;save();renderParent();showToast(P.parent==='pending'?'연결 코드를 만들었어요 · 24시간 유효':P.parent==='linked'?'보호자가 연결되었어요':'연결을 해제했어요');return;}
  if(c('[data-wipe]')){if(confirm('이 플랫폼에 저장된 내 기록(검사·관심·계획·성적·상담·설정)을 모두 지울까요? 되돌릴 수 없어요.')){['sen-explore-v1','sen-univ-v1','sen-school-v1','sen-plan-v1','sen-strategy-v1','sen-counsel-v1','sen-lib-v1','sen-news-v1','sen-trait-done',K].forEach(k=>localStorage.removeItem(k));P=LS(K,P);showToast('내 기록을 모두 지웠어요');location.reload();}return;}
});
document.addEventListener('change',e=>{const c=x=>e.target.closest(x);let b;
  if(b=c('[data-mtask]')){const co=LS('sen-counsel-v1',{tasks:{}});co.tasks[b.dataset.mtask]=true;localStorage.setItem('sen-counsel-v1',JSON.stringify(co));showToast('후속 과제를 끝냈어요 👏');renderMonth();return;}
  if(b=c('[data-al]')){P.alerts[b.dataset.al]=e.target.checked;save();b.closest('label').classList.toggle('is-on',e.target.checked);return;}
  if(e.target.id==='alDays'){P.alerts.days=+e.target.value;save();showToast(`${P.alerts.days}일 전에 알려드릴게요`);return;}
  if(b=c('[data-pshare]')){P[b.dataset.pshare]=e.target.checked;save();b.closest('label').classList.toggle('is-on',e.target.checked);return;}
  if(b=c('[data-tshare]')){const [id,k]=b.dataset.tshare.split(':');(P.teacher[id]=P.teacher[id]||{})[k]=e.target.checked;save();renderTeacher();return;}
  if(b=c('[data-ai]')){P.ai[b.dataset.ai]=e.target.checked;save();b.closest('label').classList.toggle('is-on',e.target.checked);return;}
  if(e.target.id==='pvGrade'){P.grade=e.target.value;save();showToast(`학년을 ${P.grade}(으)로 바꿨어요 · 현재 단계와 맞춤 자료가 바뀝니다`);return;}
  if(e.target.id==='pvSchool'){P.school=e.target.value;save();return;}});
setTab();
})();
