(function(){
const {ADMS,KINDS,uni,adm}=UD;const {major,drawer,store}=EX;const A=SEN_AUTH;const $=id=>document.getElementById(id);
const K='sen-strategy-v1';
const DEF=()=>({grades:{'1-1':{},'1-2':{},'2-1':{}},mock:{'2026-06':{},'2026-09':{}},rec:{},plan:{susi:[],jeongsi:{'가':null,'나':null,'다':null}},memoTeacher:'',consult:'none',interview:[]});
let P=JSON.parse(localStorage.getItem(K)||'null')||DEF();const save=()=>localStorage.setItem(K,JSON.stringify(P));
const GROUPS=['국어','수학','영어','사회','과학'];const SEMS=['1-1','1-2','2-1','2-2','3-1'];const SL={'1-1':'1학년 1학기','1-2':'1학년 2학기','2-1':'2학년 1학기','2-2':'2학년 2학기','3-1':'3학년 1학기'};
const AREAS=['국어','수학','영어','탐구1','탐구2'];const MOCKS=['2026-03','2026-06','2026-09','2026-11'];const ML={'2026-03':'3월 학평','2026-06':'6월 모평','2026-09':'9월 모평','2026-11':'11월 수능'};
/* 예시 성적 (처음 로그인 시 채움) */
if(!P.seeded){P.grades={'1-1':{국어:2,수학:3,영어:2,사회:2,과학:3},'1-2':{국어:2,수학:2,영어:2,사회:3,과학:2},'2-1':{국어:1,수학:2,영어:2,사회:2,과학:2}};P.mock={'2026-06':{국어:2,수학:3,영어:2,탐구1:2,탐구2:3},'2026-09':{국어:2,수학:2,영어:1,탐구1:2,탐구2:2}};P.rec={club:true,explore:true,volunteer:false,reading:true,award:false,career:true};P.seeded=true;save();}
const GROUP={grades:'r',record:'r',analysis:'r',convert:'c',result:'c',possible:'c',cmp:'p',plan:'p',check:'p',interview:'i',aiint:'i',exam:'i'};
const L3={grades:'내신·모의고사',record:'학생부 관련 정보',analysis:'성적·기록 분석',convert:'대학별 성적 환산',result:'입시결과 비교',possible:'지원가능성 참고분석',cmp:'관심 전형 비교',plan:'나의 지원계획',check:'지원전략 점검',interview:'면접 준비',aiint:'AI 면접 연습',exam:'대학별고사 자료'};
const L2={r:'나의 성적·기록',c:'대학별 분석',p:'지원계획',i:'면접·대학별고사'};
const OPEN=new Set(['interview','exam']);
const avg=o=>{const v=Object.values(o).filter(x=>x);return v.length?+(v.reduce((a,b)=>a+b,0)/v.length).toFixed(2):null;};
const semAvg=k=>avg(P.grades[k]||{});
const overall=()=>{const v=SEMS.map(semAvg).filter(x=>x);return v.length?+(v.reduce((a,b)=>a+b,0)/v.length).toFixed(2):null;};
const gradeSel=(k,g,v)=>`<select class="gsel" data-g="${k}" data-s="${g}" aria-label="${SL[k]||ML[k]} ${g}"><option value="">–</option>${[1,2,3,4,5].map(n=>`<option${v===n?' selected':''}>${n}</option>`).join('')}</select>`;
/* ── 내신·모의고사 ── */
let gTab='grades',D=null,dirty=false;
const snap=()=>JSON.parse(JSON.stringify({grades:P.grades,mock:P.mock}));
const ensureD=()=>{if(!D){D=snap();dirty=false;}};
const curG=()=>D?D.grades:P.grades,curM=()=>D?D.mock:P.mock;
function renderGrades(){ensureD();
  const dsemAvg=k=>avg(curG()[k]||{}),dOverall=()=>{const v=SEMS.map(dsemAvg).filter(x=>x);return v.length?+(v.reduce((a,b)=>a+b,0)/v.length).toFixed(2):null;};
  const filledG=SEMS.filter(k=>k<='2-1').reduce((n,k)=>n+GROUPS.filter(g=>(curG()[k]||{})[g]).length,0),totG=3*GROUPS.length,filledM=['2026-06','2026-09'].reduce((n,k)=>n+AREAS.filter(g=>(curM()[k]||{})[g]).length,0),totM=2*AREAS.length;
  $('gSave').innerHTML=`<div class="savebar${dirty?' is-dirty':''}"><div class="savebar__st"><i></i><b>${dirty?'수정됨 · 아직 저장되지 않았어요':P.savedAt?'저장됨 · '+P.savedAt:'아직 저장한 성적이 없어요'}</b><span>입력 ${gTab==='grades'?filledG+'/'+totG+' (교과군)':filledM+'/'+totM+' (영역)'}</span></div><div style="display:flex;gap:8px">${dirty?'<button class="btn btn--ghost btn--pill" data-gact="cancel">변경 취소</button>':''}<button class="btn btn--primary btn--pill" data-gact="save"${dirty?'':' disabled'}>저장</button></div></div>
  <div class="steps4">${[['1','입력','교과군 평균 등급 고르기'],['2','저장','저장해야 분석·상담에 반영돼요'],['3','분석 보기','성적·기록 분석에서 흐름 확인'],['4','상담 신청','입력한 성적이 사전자료로 전달']].map((x,i)=>`<div class="s4${(i===0&&dirty)||(i===1&&dirty)?' is-cur':(i<=1&&P.savedAt&&!dirty)?' is-done':''}"><i>${x[0]}</i><div><b>${x[1]}</b><span>${x[2]}</span></div></div>`).join('')}</div>`;
  $('gSeg').querySelectorAll('button').forEach(b=>b.classList.toggle('is-on',b.dataset.gt===gTab));
  if(gTab==='grades'){$('gBody').innerHTML=`<div class="ctable-w"><table class="ctable utbl gtbl"><thead><tr><th>학기</th>${GROUPS.map(g=>`<th>${g}</th>`).join('')}<th>평균</th></tr></thead><tbody>${SEMS.map(k=>{const row=curG()[k]||{},a=dsemAvg(k),fut=k>'2-1';return `<tr${fut?' style="opacity:.55"':''}><th>${SL[k]}${fut?'<div class="xcard__cat">예정</div>':''}</th>${GROUPS.map(g=>`<td>${fut?'–':gradeSel(k,g,row[g])}</td>`).join('')}<td><b>${a??'–'}</b></td></tr>`;}).join('')}</tbody></table></div>
    <div class="gsum"><div><b>${dOverall()??'–'}</b><span>전체 평균 등급</span></div><div><b>${dsemAvg('2-1')??'–'}</b><span>최근 학기</span></div><div><b>${(()=>{const a=dsemAvg('1-1'),b=dsemAvg('2-1');return a&&b?(b<a?'▲ 오름':b>a?'▼ 내림':'= 유지'):'–';})()}</b><span>1학년 → 2학년</span></div></div>
    <p class="hint">교과군별 <b>평균 등급(5등급제)</b>만 고르면 됩니다. 과목별 세부 성적·단위수·원점수는 여기서 입력하지 않아요. 상담 때 내가 동의한 범위에서 선생님이 성적 자료를 받아 함께 봅니다.</p>
    <div class="ud" style="margin-top:20px"><div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><div class="panel-c__head"><h3>최근 학기 상세 기록 (선택)</h3><small>2학년 1학기</small></div><p style="margin:0;color:var(--ink-2);font-size:14.5px">5등급제에서는 등급만으로 위치가 다 보이지 않아요. <b>원점수·과목평균·성취도·수강자 수</b>를 함께 적어 두면 상담에서 맥락을 설명하기 쉬워요.</p><div class="ctable-w"><table class="ctable utbl"><thead><tr><th>교과군</th><th>원점수</th><th>과목평균</th><th>성취도</th><th>수강자 수</th></tr></thead><tbody>${GROUPS.map(g=>{const d2=(P.detail||{})[g]||{};return `<tr><th>${g}</th><td><input class="gsel" style="width:70px" data-d2="${g}:raw" value="${d2.raw||''}" placeholder="–"></td><td><input class="gsel" style="width:70px" data-d2="${g}:avg" value="${d2.avg||''}" placeholder="–"></td><td><select class="gsel" data-d2="${g}:ach"><option value="">–</option>${['A','B','C','D','E'].map(a2=>`<option${d2.ach===a2?' selected':''}>${a2}</option>`).join('')}</select></td><td><input class="gsel" style="width:70px" data-d2="${g}:n" value="${d2.n||''}" placeholder="–"></td></tr>`;}).join('')}</tbody></table></div><p class="hint" style="margin:0">적으면 바로 저장돼요 · 분석과 상담 사전자료에 함께 전달됩니다</p></div>
    <div class="panel-c" style="background:var(--surface);box-shadow:none"><h3>5등급제, 이렇게 읽어요</h3><ul class="reading"><li><b>등급은 범위예요</b>같은 등급 안에서도 위치 차이가 커요. 한 문제 차이 경쟁은 줄었지만 맥락 평가는 커졌어요</li><li><b>원점수 − 과목평균</b>평균보다 얼마나 높은지가 등급보다 많은 걸 말해줘요</li><li><b>성취도(A~E)</b>절대평가 기준 도달 정도. 등급과 함께 보면 과목 난도가 보여요</li><li><b>수강자 수</b>수강자가 적은 과목은 등급이 쉽게 출렁여요</li><li><b>과목 선택 이유도 기록</b>난도·진로 필요·학교 개설 여건 중 무엇 때문인지 나눠 두면 상담이 쉬워져요</li></ul></div></div>`;}
  else{$('gBody').innerHTML=`<div class="ctable-w"><table class="ctable utbl gtbl"><thead><tr><th>시험</th>${AREAS.map(g=>`<th>${g}</th>`).join('')}<th>평균</th></tr></thead><tbody>${MOCKS.map(k=>{const row=curM()[k]||{},a=avg(row),fut=k>'2026-10';return `<tr${fut?' style="opacity:.55"':''}><th>${ML[k]}${fut?'<div class="xcard__cat">예정</div>':''}</th>${AREAS.map(g=>`<td>${fut?'–':gradeSel(k,g,row[g])}</td>`).join('')}<td><b>${a??'–'}</b></td></tr>`;}).join('')}</tbody></table></div>
    <div class="gsum"><div><b>${avg(curM()['2026-09']||{})??'–'}</b><span>최근 모의고사 평균</span></div><div><b>${(()=>{const m=curM()['2026-09']||{};const s=['국어','수학','탐구1'].map(k=>m[k]).filter(Boolean);return s.length===3?s.reduce((a,b)=>a+b,0):'–';})()}</b><span>국·수·탐1 등급합 (참고)</span></div><div><b>${(()=>{const a=avg(curM()['2026-06']||{}),b=avg(curM()['2026-09']||{});return a&&b?(b<a?'▲ 오름':b>a?'▼ 내림':'= 유지'):'–';})()}</b><span>6월 → 9월</span></div></div>
    <p class="hint">영역별 <b>등급</b>만 입력합니다. 표준점수·백분위는 수능최저 확인과 정시 환산에 쓰이는 값이라 상담에서 선생님이 다룹니다.</p>`;}
}
/* ── 학생부 관련 정보 ── */
const REC=[['club','진로와 이어지는 동아리 활동이 있어요','학종에서 진로 연계 활동을 봐요'],['explore','수업 중 탐구·발표 활동을 꾸준히 했어요','세특에 기록되는 내용이에요'],['reading','진로 관련 책을 읽고 기록했어요','독서 활동은 2024학년도부터 대입 미반영이지만 세특 연계는 가능해요'],['volunteer','교내 봉사·학급 활동에 참여했어요','개인 봉사는 미반영, 교내 활동 중심이에요'],['award','교과·탐구 관련 교내 수상이 있어요','수상 경력은 대입 미반영 항목이에요'],['career','진로 희망과 선택과목이 일관돼요','진로선택 과목 이수 흐름을 봐요']];
function renderRecord(){const n=REC.filter(r=>P.rec[r[0]]).length;
  $('recBody').innerHTML=`<div class="ud"><div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><div class="panel-c__head"><h3>내 학교생활 돌아보기</h3><small>${n}/${REC.length}</small></div><p style="margin:0;color:var(--ink-2);font-size:14.5px">학생부 원문은 여기에 입력하지 않아요. 상담 때는 <b>내가 동의한 범위</b>에서 선생님이 학생부 자료를 받아 함께 봅니다. 학교 선생님은 NEIS에서 보고, 센터 상담은 내가 동의하거나 직접 가져온 자료로 봐요. 여기서는 내가 기억하는 활동을 체크해 상담 전 이야깃거리를 만들어요.</p><div class="lchips" style="margin-top:4px"><a href="#" data-toast="나이스플러스(학생서비스)로 이동합니다 · 재학 학교급 전년도 학생부를 볼 수 있어요">나이스플러스에서 내 학생부 보기 ↗</a><a href="my.html#privacy">상담 공유 범위 설정 ›</a></div><p style="display:none"></p><div class="reclist">${REC.map(r=>`<label class="cbx${P.rec[r[0]]?' is-on':''}" style="min-width:0;align-items:flex-start"><input type="checkbox" data-rec="${r[0]}"${P.rec[r[0]]?' checked':''}><span><b style="display:block">${r[1]}</b><small style="color:var(--ink-3)">${r[2]}</small></span></label>`).join('')}</div></div>
  <div><div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><h3>학생부, 무엇을 보나요?</h3><ul class="reading"><li><b>교과 학습발달 (세특)</b>과목별 성취와 수업 중 모습. 학종에서 가장 비중이 커요</li><li><b>창의적 체험활동</b>자율·동아리·진로 활동. 교내 활동 중심으로 기록돼요</li><li><b>행동특성 및 종합의견</b>담임 선생님이 1년을 정리한 글</li><li><b>미반영 항목</b>수상 경력, 개인 봉사, 독서, 자율동아리는 대입에 반영되지 않아요 (2024학년도~)</li></ul></div>
  <div class="panel-c" style="margin-top:16px;border:1.5px solid #5B3FD6;box-shadow:none"><div class="panel-c__head"><h3>🤖 생기부 자가진단 <span class="tb" style="background:#F0EBFF;color:#5B3FD6">AI PoC</span></h3></div><p style="margin:0;color:var(--ink-2);font-size:14.5px">세특·창체 기록을 붙여 넣으면 브라우저 안에서 비식별 처리한 뒤 가명·합성 데이터로 학업·진로·공동체 역량을 분석해요. 선생님 의견이 아니고, 학생부 기재는 교사가 결정합니다.</p><a class="btn btn--primary btn--pill" href="sen-ai-poc.html#rec" style="align-self:flex-start;background:#5B3FD6">생기부 어시스턴트 열기 →</a></div>
  <div class="band" style="margin-top:16px;padding:24px 28px"><div><h2 style="font-size:20px">내 학생부를 함께 읽어볼까요?</h2><p>체크한 내용이 상담 사전자료로 전달됩니다</p></div><a class="btn btn--primary btn--pill" href="counsel.html#book">학생부 상담 신청</a></div></div></div>`;}
/* ── 성적·기록 분석 ── */
function renderAnalysis(){const sems=SEMS.filter(k=>semAvg(k));const W=560,H=220,pad=44;
  const pts=sems.map((k,i)=>[pad+i*(W-pad*2)/Math.max(1,sems.length-1),pad+(semAvg(k)-1)/4*(H-pad*2)]);
  const line=pts.map((p,i)=>(i?'L':'M')+p[0]+','+p[1]).join(' ');
  const gAvg=GROUPS.map(g=>{const v=sems.map(k=>P.grades[k][g]).filter(Boolean);return [g,v.length?+(v.reduce((a,b)=>a+b,0)/v.length).toFixed(1):null];}).filter(x=>x[1]);
  const best=gAvg.slice().sort((a,b)=>a[1]-b[1]);
  const m9=P.mock['2026-09']||{},mAvg=avg(m9),ov=overall();
  $('anBody').innerHTML=`<div class="ud"><div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><div class="panel-c__head"><h3>학기별 평균 등급 흐름</h3><small>1등급이 위</small></div><svg viewBox="0 0 ${W} ${H}" class="chart" aria-label="학기별 평균 등급">${[1,2,3,4,5].map(g=>{const y=pad+(g-1)/4*(H-pad*2);return `<line x1="${pad}" x2="${W-pad}" y1="${y}" y2="${y}" stroke="var(--line)"/><text x="${pad-8}" y="${y+4}" text-anchor="end" font-size="11" fill="var(--ink-3)">${g}</text>`;}).join('')}<path d="${line}" fill="none" stroke="var(--brand)" stroke-width="3"/>${pts.map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="6" fill="#fff" stroke="var(--brand)" stroke-width="3"/><text x="${p[0]}" y="${p[1]-12}" text-anchor="middle" font-size="12" font-weight="800" fill="var(--ink)">${semAvg(sems[i])}</text><text x="${p[0]}" y="${H-10}" text-anchor="middle" font-size="11" fill="var(--ink-3)">${sems[i]}</text>`).join('')}</svg></div>
  <div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><div class="panel-c__head"><h3>교과군별 평균</h3><small>낮을수록 좋아요</small></div><div style="display:flex;flex-direction:column;gap:10px">${gAvg.map(([g,v],i)=>`<div class="bar${best[0][0]===g?' is-top':''}" style="grid-template-columns:48px 1fr 40px"><span>${g}</span><div class="bar__track"><div class="bar__fill" style="width:${(6-v)/5*100}%"></div></div><span class="bar__val">${v}</span></div>`).join('')}</div></div></div>
  <div class="ud" style="margin-top:20px"><div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><h3>이렇게 읽어보세요</h3><ul class="reading"><li><b>강한 교과군은 ${best[0][0]}(${best[0][1]}등급)</b>${best[0][0]} 관련 학과·전형을 살펴볼 때 참고가 돼요</li><li><b>${best[best.length-1][0]}은 ${best[best.length-1][1]}등급</b>목표 학과에서 중요한 교과라면 상담에서 보완 방법을 물어보세요</li><li><b>내신 ${ov} · 모의고사 ${mAvg??'–'}</b>${ov&&mAvg?(mAvg<ov-0.3?'모의고사가 더 좋은 편이에요. 정시·수능최저 활용 전형을 함께 살펴볼 만해요':ov<mAvg-0.3?'내신이 더 좋은 편이에요. 학생부 중심 전형을 먼저 살펴볼 만해요':'내신과 모의고사가 비슷해요. 두 가지 길을 모두 열어두세요'):'모의고사를 입력하면 비교해 드려요'}</li></ul></div>
  <div class="panel-c" style="background:var(--surface);box-shadow:none"><h3>학생부 돌아보기 결과</h3><p style="margin:0;color:var(--ink-2)">${REC.filter(r=>P.rec[r[0]]).length}개 항목을 체크했어요. ${P.rec.career?'진로 희망과 선택과목이 일관된다고 표시했어요. 학종에서 좋게 볼 수 있는 흐름이에요.':'진로와 선택과목의 연결을 상담에서 함께 점검해 보세요.'}</p><a class="link" href="#record">학생부 돌아보기 ›</a></div></div>
  <div class="panel-c" style="margin-top:20px;border:1px solid var(--line);box-shadow:none"><div class="panel-c__head"><h3>정시 안정도 (참고)</h3><small>모의고사 3회 이상 기준</small></div>${(()=>{const taken=MOCKS.filter(k=>Object.values(P.mock[k]||{}).some(Boolean)),avgs=taken.map(k=>avg(P.mock[k]));if(taken.length<3)return `<p class="hint" style="margin:0">지금까지 ${taken.length}회 입력했어요. 모의고사를 3회 이상 입력하면 평균과 흔들림(편차)으로 안정도를 보여드려요. 한 번 성적이 아니라 여러 번의 흐름이 기준이에요.</p>`;const mean=+(avgs.reduce((a,b)=>a+b,0)/avgs.length).toFixed(2),dev=+(Math.max(...avgs)-Math.min(...avgs)).toFixed(1);const lv=dev<=0.5?['안정','#0E8A57','시험 간 흔들림이 작아 기존 점수를 기준으로 삼을 만해요']:dev<=1?['비교적 안정','#B7791F','조금 흔들려요. 평균을 기준으로 하되 보수 구간도 함께 봐요']:['불안정','#C43B3B','흔들림이 커서 기존 점수의 의미가 줄어요. 보수적으로 잡고 상담에서 원인을 봐요'];return `<div class="lchips">${taken.map((k,i)=>`<span>${ML[k]} 평균 ${avgs[i]}</span>`).join('')}</div><p style="margin:8px 0 0;color:var(--ink-2);font-size:14.5px">평균 <b>${mean}</b> · 편차(최대−최소) <b>${dev}</b> → <b style="color:${lv[1]}">${lv[0]}</b>. ${lv[2]}</p><p class="hint" style="margin:8px 0 0">구간 기준(0.5 / 1.0등급)은 설정값이에요. 공식 기준이 아니고, 정확한 판단은 백분위·표준점수로 상담에서 합니다.</p>`;})()}</div>
  <div class="notice" style="margin-top:20px"><div class="notice__icon">💡</div><div><h3>이 분석은 '내가 입력한 등급'으로만 계산한 참고 자료예요</h3><p>단위수, 원점수, 과목별 석차, 학생부 원문은 반영되지 않았어요. 정확한 분석과 지원 전략은 상담에서 선생님이 내가 동의한 성적·학생부 자료로 함께 봅니다.</p></div></div>`;}
/* ── 대학별 성적 환산 ── */
function renderConvert(){const mine=S_adms();
  $('cvBody').innerHTML=`<div class="ud"><div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><h3>환산, 왜 대학마다 다를까요?</h3><ul class="reading"><li><b>반영 교과</b>국·수·영·사·과 중 어떤 교과를 넣는지, 전 과목인지 상위 몇 과목인지</li><li><b>등급별 점수</b>1등급과 2등급의 점수 차이가 대학마다 달라요</li><li><b>진로선택 과목</b>성취도(A·B·C)를 어떻게 점수로 바꾸는지</li><li><b>학년별 비율</b>3학년 성적을 더 크게 보는 대학도 있어요</li></ul><p class="hint" style="margin:0">같은 내신이라도 대학에 따라 유리·불리가 갈리는 이유예요.</p></div>
  <div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><div class="panel-c__head"><h3>관심 전형의 환산 방식</h3><small>${mine.length}개</small></div>${mine.length?`<div class="alist">${mine.map(a=>{const u=uni(a.uni);return `<div class="arow" style="cursor:default"><span class="tb tb--${a.season==='수시'?1:2}">${a.season}</span><div><b>${u.name} · ${a.name}</b><span>${a.elems.map(e=>e[0]+' '+e[1]+'%').join(' + ')}${a.kind==='학생부교과'?' · 반영 교과: 국·수·영·사/과 (예시)':a.kind==='수능'?' · 반영영역: '+a.sat.join('·'):' · 정성 평가 (환산점 없음)'}</span></div><span class="arow__min">${a.kind==='학생부교과'||a.kind==='수능'?'환산 가능':'정성평가'}</span></div>`;}).join('')}</div>`:'<p class="hint">전형정보에서 관심 전형을 저장하면 환산 방식을 모아 보여드려요. <a class="link" href="univ.html#susi">전형 찾기 ›</a></p>'}</div></div>
  <div class="lockbox"><div class="lockbox__ic">🔒</div><div><h3>환산 점수 계산은 상담에서 선생님이 해드려요</h3><p>대학별 환산 점수는 과목별 세부 성적과 당해 연도 요강 확정값이 필요해서, 선생님이 업무시스템에서 계산해 상담 때 보여드립니다. 여기서 '환산 요청'을 남기면 상담 사전자료로 전달돼요.</p></div><button class="btn btn--primary btn--pill" data-req="convert">환산 요청하고 상담 신청</button></div>`;}
/* ── 입시결과 비교 (3개년) ── */
function renderResult(){const ov=overall(),mine=S_adms().filter(a=>a.season==='수시'&&a.prev!=null);
  const yr=a=>{const h=[...a.id].reduce((x,c2)=>x+c2.charCodeAt(0),0),p=Object.values(a.perMajor)[0];
    const mk=(off,dq,dc)=>({q:18+(h+off)%14,comp:+(4+((h*7+off*13)%60)/10).toFixed(1),fill:55+(h*3+off*17)%45,c50:+(p.prev50+dq).toFixed(1),c70:+(p.prev70+dc).toFixed(1)});
    return [['2024',mk(1,0.2,0.1)],['2025',mk(2,0.1,h%4===0?0.5:0.1)],['2026',mk(3,0,0)]];};
  $('rsBody').innerHTML=`<div class="rbar" style="margin-top:0"><div><b>내 내신 평균 ${ov??'–'}등급</b> <span class="hint" style="margin:0">(5등급제 · 교과군 평균 기준)</span></div><a class="link" href="univ.html#susi">전형 더 찾기 ›</a></div>
  ${mine.length?mine.map(a=>{const u=uni(a.uni),Y=yr(a),last=Y[2][1],avg70=+(Y.reduce((s,y)=>s+y[1].c70,0)/3).toFixed(1);
    const gaps=Y.map(y=>+(y[1].c70-y[1].c50).toFixed(1)),gapW=gaps[2]>gaps[0]+0.3||gaps[1]>gaps[0]+0.3;
    const d=ov?+(ov-last.c70).toFixed(1):null;
    return `<div class="panel-c" style="margin-top:16px;border:1px solid var(--line);box-shadow:none"><div class="panel-c__head"><div><h3>${u.name} · ${a.name}</h3><small>${a.kind} · 3개년 비교 (예시 데이터)</small></div>${gapW?'<span class="st" style="background:#FDEBEC;color:#C43B3B">⚠ 컷 간격 급변 · 상담 확인</span>':''}</div>
    <div class="ctable-w"><table class="ctable utbl"><thead><tr><th>학년도</th><th>모집인원</th><th>경쟁률</th><th>충원율</th><th>50% 컷</th><th>70% 컷</th></tr></thead><tbody>${Y.map(([y,v],i)=>`<tr${i===2?' style="font-weight:700"':''}><th>${y}</th><td>${v.q}명</td><td>${v.comp}:1</td><td>${v.fill}%</td><td>${v.c50}</td><td>${v.c70}</td></tr>`).join('')}</tbody></table></div>
    <p style="margin:0;color:var(--ink-2);font-size:14px">3개년 70% 컷 평균 <b>${avg70}</b> · 직전 연도는 평균${last.c70<avg70?'보다 높아요 (컷이 올라감)':last.c70>avg70?'보다 낮아요 (컷이 내려감)':'과 비슷해요'}${d!=null?` · 내 평균과의 거리 <b>${d<=0?'컷 안쪽':'컷보다 '+d+'등급 아래'}</b> (참고)`:''}</p>
    ${gapW?'<p class="hint" style="margin:0">50%·70% 컷 간격이 전보다 벌어졌어요. 합격선이 출렁였을 수 있으니 한 해 수치로 판단하지 말고 상담에서 확인하세요. (간격 기준 ±0.3은 설정값이에요)</p>':''}</div>`;}).join(''):'<div class="empty-r"><b>관심 전형이 없어요</b>전형정보에서 🤍를 눌러 저장하면 3개년 결과를 나란히 보여드려요.</div>'}
  <div class="notice" style="margin-top:20px"><div class="notice__icon">⚠️</div><div><h3>입결은 합격을 예언하는 점수가 아니에요</h3><p>최소 3개년의 모집인원·충원율·경쟁률·컷을 함께 봐야 해요. 학종 입결은 여러 고교 유형이 섞인 수치라 그대로 내게 적용하면 오류가 생기고, 소수 모집단위의 한 해 최저점을 안정 기준으로 쓰면 안 돼요. 지원 여부는 반드시 상담에서 정하세요.</p></div></div>`;}
/* ── 지원가능성 참고분석 (선생님 상담 결과만 표시) ── */
function renderPossible(){const st=P.consult;
  $('psBody').innerHTML=st==='done'?`<div class="uhead" style="align-items:center"><div><small>2026.09.30 · 이진로 선생님 상담 결과</small><h2 style="font-size:22px">상담에서 정리한 참고 범위</h2><p style="margin:0;color:var(--ink-2)">선생님이 성적·학생부·요강을 함께 보고 정리해 준 내용이에요. 합격을 보장하는 판정이 아니라, 지원 계획을 세울 때 참고하는 범위입니다.</p></div><button class="btn btn--ghost btn--pill" href="my.html#counsel">상담 기록 보기</button></div>
    <div class="psgrid">${[['살펴볼 만해요','a4','내신 흐름과 반영 교과가 잘 맞는 편. 수능최저 2합 5 충족 여부가 핵심'],['살펴볼 만해요','a2','학생부 진로 연계가 좋아 서류 경쟁력 있음. 면접 준비 필요'],['도전해 볼 만해요','a1','학교장 추천 인원 확인 필요. 최저 3합 7은 현재 모의고사로 가능 범위'],['신중하게','a16','전년도 결과와 거리가 있음. 지원한다면 다른 카드와 균형 필요']].map(([lv,id,note])=>{const a=adm(id),u=uni(a.uni);return `<div class="pscard"><span class="lv lv--${lv==='살펴볼 만해요'?'hi':lv==='도전해 볼 만해요'?'mid':'low'}">${lv}</span><b>${u.name}</b><span>${a.name} · ${a.kind}</span><p>${note}</p><button class="mini" data-addplan="${id}">지원계획에 담기</button></div>`;}).join('')}</div>
    <div class="band" style="margin-top:20px;padding:24px 28px"><div><h2 style="font-size:20px">다음 상담은 수시 원서 접수 전에</h2><p>9월 모의고사 결과를 반영해 범위를 다시 봅니다</p></div><a class="btn btn--primary btn--pill" href="counsel.html#book">다음 상담 예약</a></div>`
  :`<div class="lockbox" style="margin-top:0"><div class="lockbox__ic">${st==='req'?'⏳':'🗣️'}</div><div><h3>${st==='req'?'상담 신청이 접수되었어요':'지원가능성은 상담에서 선생님과 함께 봅니다'}</h3><p>${st==='req'?'선생님이 성적·학생부·요강을 보고 상담 때 참고 범위를 정리해 드려요. 상담이 끝나면 이 화면에 결과가 표시됩니다.':'이 화면은 자동으로 합격 가능성을 계산하지 않아요. 내 성적과 학생부를 아는 선생님이 상담에서 정리한 참고 범위만 보여드립니다. 그래야 숫자 하나에 흔들리지 않고 계획을 세울 수 있어요.'}</p><div style="display:flex;gap:8px;flex-wrap:wrap">${st==='req'?'<button class="btn btn--ghost btn--pill" data-consult="done">(목업) 상담 완료 상태 보기</button>':'<button class="btn btn--primary btn--pill" data-consult="req">상담 신청하기</button><button class="btn btn--ghost btn--pill" data-consult="done">(목업) 상담 완료 상태 보기</button>'}</div></div></div>
    <div class="preview" style="margin-top:20px"><div><span class="tb tb--1">1</span><b>성적·학생부 입력</b><span>교과군 평균과 학교생활 체크만 하면 돼요</span></div><div><span class="tb tb--2">2</span><b>상담 신청</b><span>입력한 내용과 관심 전형이 선생님께 전달돼요</span></div><div><span class="tb tb--3">3</span><b>참고 범위 확인</b><span>상담 후 이 화면에서 정리된 범위를 봐요</span></div></div>`;}
/* ── 관심 전형 비교 ── */
const S_adms=()=>{const s=JSON.parse(localStorage.getItem('sen-univ-v1')||'{"adms":[]}');return s.adms.map(adm).filter(Boolean);};
function renderCmp(){const mine=S_adms();
  $('cmBody').innerHTML=mine.length?`<div class="ctable-w"><table class="ctable utbl"><thead><tr><th>전형</th><th>시기</th><th>방법</th><th>수능최저</th><th>면접</th><th>원서 접수 (예시)</th><th>전년도</th><th>지원계획</th></tr></thead><tbody>${mine.map(a=>{const u=uni(a.uni),inPlan=P.plan.susi.includes(a.id)||Object.values(P.plan.jeongsi).includes(a.id);return `<tr class="trow" data-adm="${a.id}"><td><b>${u.name}</b><div class="xcard__cat">${a.name}</div></td><td>${a.season==='수시'?'수시':'정시 '+a.group}</td><td>${a.elems.map(e=>e[0]+' '+e[1]).join('+')}</td><td>${a.minType==='반영안함'?'없음':'<b>있음</b>'}</td><td>${a.docs.includes('면접')?'<b>있음</b>':'없음'}</td><td>${a.season==='수시'?'9.8~9.12':'12.29~12.31'}</td><td>${a.prev!=null?a.prev.toFixed(1):'–'}</td><td><button class="mini${inPlan?' is-on':''}" data-addplan="${a.id}">${inPlan?'✓ 담김':'담기'}</button></td></tr>`;}).join('')}</tbody></table></div><p class="hint">전형정보에서 저장한 관심 전형입니다. 요건을 나란히 보고 지원계획에 담아 보세요. 유불리는 상담에서 봅니다</p>`:'<div class="empty-r"><b>관심 전형이 없어요</b><a class="link" href="univ.html#susi">전형정보에서 저장하기 ›</a></div>';}
/* ── 나의 지원계획 ── */
function renderPlan(){const S6=P.plan.susi,J=P.plan.jeongsi;
  const card=(id,slot)=>{if(!id)return `<div class="slot slot--empty" data-slot="${slot}"><span>+</span><small>${slot.startsWith('s')?'수시 '+(+slot.slice(1)+1)+'번째':'정시 '+slot+'군'}</small></div>`;const a=adm(id),u=uni(a.uni);return `<div class="slot" data-adm="${id}"><span class="tb tb--${a.season==='수시'?1:2}">${a.kind}</span><b>${u.name}</b><span>${a.name}</span><div class="slot__tags">${a.minType!=='반영안함'?'<i>최저</i>':''}${a.docs.includes('면접')?'<i>면접</i>':''}${a.docs.includes('논술')?'<i>논술</i>':''}</div><button class="slot__x" data-rmplan="${id}" aria-label="빼기">✕</button></div>`;};
  const kinds={};S6.map(adm).forEach(a=>kinds[a.kind]=(kinds[a.kind]||0)+1);
  $('plBody').innerHTML=`<div class="rbar" style="margin-top:0"><div><h3 style="margin:0;font-size:20px">수시 <span style="color:var(--brand)">${S6.length}</span>/6</h3><p class="section__sub" style="font-size:14px">관심 전형 비교에서 '담기'로 채워요 · 빈 칸을 누르면 관심 전형 비교로 이동해요</p></div><div class="fchips">${Object.entries(kinds).map(([k,n])=>`<span class="chip">${k} ${n}</span>`).join('')}</div></div>
  <div class="slots">${Array.from({length:6},(_,i)=>card(S6[i],'s'+i)).join('')}</div>
  ${S6.length?`<div class="panel-c" style="margin:20px 0 4px;border:1px solid var(--line);box-shadow:none"><div class="panel-c__head"><h3>지원 매트릭스</h3><small>조건부 시나리오로 보기</small></div><p style="margin:0;color:var(--ink-2);font-size:14.5px">수시 6장은 상향·적정·안정 비율 공식이 아니라 <b>탈락 원인을 분산하는 여섯 개의 판단</b>이에요. 카드마다 등록 의사·최저 충족·면접일·주된 위험을 적어요.</p><div class="ctable-w"><table class="ctable utbl"><thead><tr><th>카드</th><th>합격 시 등록 의사</th><th>최저 충족 (최근 3회 기준)</th><th>면접일</th><th>주된 탈락 위험</th></tr></thead><tbody>${S6.map(id=>{const a=adm(id),u=uni(a.uni),m=(P.mx||{})[id]||{};const sel=(k,opts)=>`<select class="gsel" data-mx="${id}:${k}"><option value="">–</option>${opts.map(o=>`<option${m[k]===o?' selected':''}>${o}</option>`).join('')}</select>`;return `<tr><th><b>${u.name}</b><div class="xcard__cat">${a.name}</div></th><td>${sel('reg',['등록할게요','고민 필요','아직 모름'])}</td><td>${a.minType==='반영안함'?'<span class="hint" style="margin:0">최저 없음</span>':sel('min',['가능','빠뛯함','어려움'])}</td><td>${a.docs.includes('면접')?`<input class="gsel" style="width:88px" data-mx="${id}:iv" value="${m.iv||''}" placeholder="11.22">`:'<span class="hint" style="margin:0">면접 없음</span>'}</td><td>${sel('risk',['수능최저','면접','서류·교과','경쟁률','기타'])}</td></tr>`;}).join('')}</tbody></table></div>${(()=>{const mx=P.mx||{},risks=S6.map(id=>(mx[id]||{}).risk).filter(Boolean),rc={};risks.forEach(r=>rc[r]=(rc[r]||0)+1);const ivs=S6.map(id=>(mx[id]||{}).iv).filter(Boolean),dup=[...new Set(ivs.filter((d2,i)=>ivs.indexOf(d2)!==i))];return `<div class="lchips">${Object.entries(rc).map(([k,n])=>`<span${n>=3?' style="background:#FDEBEC;color:#C43B3B"':''}>위험: ${k} ${n}장</span>`).join('')}${dup.length?`<span style="background:#FDEBEC;color:#C43B3B">면접일 겹침: ${dup.join(', ')}</span>`:''}</div><p class="hint" style="margin:0">같은 위험에 3장 이상 몰리면 한 원인으로 한꺼번에 떨어질 수 있어요. 등록 의사와 위험 감수 수준은 보호자와 합의해요(보호자 연결 시 함께 보여요). 최종 판단은 상담에서 합니다.</p>`;})()}</div>`:''}
  <div class="rbar"><div><h3 style="margin:0;font-size:20px">정시 <span style="color:var(--brand)">${Object.values(J).filter(Boolean).length}</span>/3</h3><p class="section__sub" style="font-size:14px">가·나·다군 각 1곳</p></div></div>
  <div class="slots slots--3">${['가','나','다'].map(g=>card(J[g],g)).join('')}</div>
  <div class="ud" style="margin-top:24px"><div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><h3>선생님께 보내기</h3><p style="margin:0;color:var(--ink-2);font-size:14.5px">지원계획을 보내면 선생님이 상담 전에 미리 살펴봅니다. 최종 결정은 상담에서 함께 해요.</p><textarea class="memo" id="plMemo" placeholder="궁금한 점 (예: 최저 없는 전형을 하나 더 넣는 게 좋을까요?)">${P.memoTeacher||''}</textarea><button class="btn btn--primary btn--pill" id="plSend">지원계획 보내고 상담 신청</button></div>
  <div class="panel-c" style="background:var(--surface);box-shadow:none"><h3>지원계획 점검으로</h3><p style="margin:0;color:var(--ink-2);font-size:14.5px">최저·면접 일정·전형 쏠림 등 함께 살펴볼 점을 정리해 드려요.</p><a class="btn btn--ghost btn--pill" href="#check" style="align-self:flex-start">점검 보기 →</a></div></div>`;}
/* ── 지원전략 점검 (질문형) ── */
function renderCheck(){const S6=P.plan.susi.map(adm),J=Object.values(P.plan.jeongsi).filter(Boolean).map(adm),all=[...S6,...J],out=[];
  if(!S6.length)out.push(['q','수시 지원계획이 비어 있어요','관심 전형 비교에서 담아보세요']);
  const minN=S6.filter(a=>a.minType!=='반영안함').length;if(S6.length&&minN===S6.length)out.push(['q','수시 6장이 모두 수능최저가 있는 전형이에요','최저를 못 맞추면 모두 무효가 될 수 있어요. 최저 없는 전형을 섞을지 상담에서 물어보세요']);
  const kinds=new Set(S6.map(a=>a.kind));if(S6.length>=4&&kinds.size===1)out.push(['q',`수시가 모두 ${[...kinds][0]} 전형이에요`,'한 유형에 몰려 있어요. 의도한 것인지 선생님과 확인해 보세요']);
  const iv=S6.filter(a=>a.docs.includes('면접'));if(iv.length>=3)out.push(['q',`면접이 있는 전형이 ${iv.length}개예요`,'면접 날짜가 겹칠 수 있어요. 요강에서 일정을 확인하고 상담에서 조정하세요']);
  const rec=S6.filter(a=>a.reqNote&&a.reqNote.includes('추천'));if(rec.length)out.push(['q',`학교장 추천이 필요한 전형 ${rec.length}개`,rec.map(a=>uni(a.uni).name).join(', ')+' · 추천 인원에 들 수 있는지 담임 선생님께 확인하세요']);
  const reg=S6.filter(a=>a.reqNote&&a.reqNote.includes('지역'));if(reg.length)out.push(['q','지역 요건이 있는 전형이 있어요',reg.map(a=>uni(a.uni).name).join(', ')+' · 서울 고교 재학생은 지원 자격을 꼭 확인하세요']);
  const mx=P.mx||{},risks=P.plan.susi.map(id=>(mx[id]||{}).risk).filter(Boolean),rc={};risks.forEach(r=>rc[r]=(rc[r]||0)+1);const topR=Object.entries(rc).sort((a,b)=>b[1]-a[1])[0];
  if(topR&&topR[1]>=3)out.push(['q',`'${topR[0]}' 위험에 ${topR[1]}장이 몰려 있어요`,'같은 원인으로 한꺼번에 떨어질 수 있어요. 탈락 원인을 분산하도록 상담에서 조정해 보세요']);
  const ivds=P.plan.susi.map(id=>(mx[id]||{}).iv).filter(Boolean),dup=[...new Set(ivds.filter((d2,i)=>ivds.indexOf(d2)!==i))];
  if(dup.length)out.push(['q','지원 매트릭스에 면접일이 같은 전형이 있어요',dup.join(', ')+' · 요강에서 시간대를 확인하고 상담에서 조정하세요']);
  const regW=P.plan.susi.map(id=>(mx[id]||{}).reg);if(P.plan.susi.length>=4&&regW.filter(r=>r==='아직 모름').length>=3)out.push(['q','등록 의사를 정하지 않은 카드가 많아요','합격해도 등록하지 않을 카드는 기회를 줌여요. 가족과 등록 의사를 먼저 합의하세요']);
  const unis=new Set(all.map(a=>a.uni));out.push(['info',`대학 ${unis.size}곳 · 수시 ${S6.length}장 · 정시 ${J.length}장`,'전체 구성을 상담에서 함께 봐요']);
  if(!out.some(c=>c[0]==='q'))out.unshift(['ok','특별히 걸리는 점은 없어 보여요','그래도 최종 확인은 선생님과 함께 하세요']);
  $('ckBody').innerHTML=`<div class="cks" style="margin-top:0">${out.map(c=>`<div class="ck ck--${c[0]}"><i>${c[0]==='ok'?'✓':c[0]==='q'?'?':'i'}</i><div><b>${c[1]}</b>${c[2]?`<span>${c[2]}</span>`:''}</div></div>`).join('')}</div>
  <div class="ud" style="margin-top:20px"><div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><h3>원서 접수 전 확인 목록</h3><div class="reclist">${[['원서 접수 기간과 대학별 마감 시간을 적어 두었어요'],['수능최저가 있는 전형은 필요한 등급합을 알고 있어요'],['면접·논술·실기 날짜가 서로 겹치지 않아요'],['학교장 추천 전형은 학교에 추천 신청을 했어요'],['자기소개서 등 제출 서류(해당 시)를 확인했어요'],['지원계획을 선생님·보호자와 이야기했어요']].map((x,i)=>`<label class="cbx" style="min-width:0"><input type="checkbox" data-ckl="${i}"${(P.ckl||[]).includes(i)?' checked':''}><span>${x[0]}</span></label>`).join('')}</div></div>
  <div class="band" style="padding:24px 28px;align-self:start"><div><h2 style="font-size:20px">점검 결과를 들고 상담하세요</h2><p>살펴볼 점과 체크 목록이 사전자료로 전달됩니다</p></div><a class="btn btn--primary btn--pill" href="counsel.html#book">상담 신청</a></div></div>`;}
/* ── 면접 준비 ── */
const IVTYPES=[['서류 기반 면접','학생부 내용을 바탕으로 질문해요. 내가 한 활동을 내 말로 설명할 수 있으면 돼요',['이 활동을 하게 된 계기는?','가장 어려웠던 점과 해결 방법은?','이 경험이 지원 학과와 어떻게 이어지나요?']],['제시문 기반 면접','글이나 자료를 읽고 생각을 말해요. 논리적으로 정리하는 연습이 필요해요',['제시문의 핵심 주장을 요약해 보세요','두 입장 중 어느 쪽에 동의하나요? 이유는?','이 문제를 해결할 다른 방법이 있을까요?']],['교직 적성·인성 면접','교사가 되려는 이유와 가치관을 봐요',['왜 교사가 되고 싶나요?','학생이 수업을 방해하면 어떻게 할 건가요?','좋은 교사란 무엇이라고 생각하나요?']]];
function renderInterview(){const mine=S_adms().filter(a=>a.docs.includes('면접'));
  $('ivBody').innerHTML=`<div class="rbar" style="margin-top:0"><div><h3 style="margin:0;font-size:20px">면접이 있는 내 관심 전형</h3></div></div>${A.logged()?(mine.length?`<div class="alist">${mine.map(a=>{const u=uni(a.uni);return `<div class="arow" data-adm="${a.id}"><span class="tb tb--1">${a.season}</span><div><b>${u.name} · ${a.name}</b><span>면접 ${a.elems.find(e=>e[0]==='면접')?.[1]||''}% · ${a.stage} · ${a.kind==='학생부종합'?'서류 기반 면접 (예시)':'교직 적성·인성 면접 (예시)'}</span></div><i>›</i></div>`;}).join('')}</div>`:'<p class="hint">면접이 있는 관심 전형이 아직 없어요. <a class="link" href="univ.html#susi">전형 찾기 ›</a></p>'):'<p class="hint"><a class="link" href="#" data-loginopen>로그인</a>하면 관심 전형의 면접 유형을 보여드려요</p>'}
  <h3 class="lib__h">면접 유형별로 준비하기</h3><div class="ivtypes">${IVTYPES.map((t,i)=>`<div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><h3>${t[0]}</h3><p style="margin:0;color:var(--ink-2);font-size:14.5px">${t[1]}</p><b style="font-size:13px;color:var(--ink-3)">자주 나오는 질문</b><ul style="margin:0;padding-left:18px;color:var(--ink-2);font-size:14.5px;display:flex;flex-direction:column;gap:4px">${t[2].map(q=>`<li>${q}</li>`).join('')}</ul><a class="btn btn--ghost btn--pill" href="#aiint" data-ivset="${i}" style="align-self:flex-start">이 유형으로 연습 →</a></div>`).join('')}</div>
  <div class="ud" style="margin-top:20px"><div class="panel-c" style="border:1px solid var(--line);box-shadow:none"><h3>나만의 예상 질문 만들기</h3><p style="margin:0;color:var(--ink-2);font-size:14.5px">학생부 돌아보기에서 체크한 활동을 질문으로 바꿔 보세요.</p><ul class="reading">${REC.filter(r=>P.rec[r[0]]).slice(0,3).map(r=>`<li><b>Q. ${r[1].replace('있어요','있다고 했는데, 구체적으로 어떤 활동이었나요?').replace('했어요','했다고 했는데, 기억에 남는 순간은?').replace('돼요','된다고 했는데, 어떻게 연결되나요?')}</b></li>`).join('')||'<li>학생부 돌아보기에서 활동을 체크하면 질문을 만들어 드려요</li>'}</ul><a class="link" href="#record">학생부 돌아보기 ›</a>${(()=>{const ns=JSON.parse(localStorage.getItem('sen-notes-v1')||'[]');return ns.length?`<b style="font-size:13px;color:var(--ink-3)">활동 성장 노트로 만든 질문</b><ul class="reading">${ns.slice(-3).reverse().map(n=>`<li><b>Q. '${n.title}'에서 처음 질문은 무엇이었고, 생각이 어떻게 바뀌었나요?</b>${n.f&&n.f.chg?'내 기록: '+n.f.chg:''}</li>`).join('')}</ul>`:'<p class="hint" style="margin:0"><a class="link" href="my.html#notes">활동 성장 노트</a>를 쓰면 내 활동으로 면접 질문을 만들어 드려요</p>';})()}<div style="background:var(--surface);border-radius:12px;padding:12px 14px;font-size:13.5px;color:var(--ink-2)"><b style="color:var(--ink)">60초 설명 틀</b> — ① 무엇이 궁금했나 ② 어떤 자료·피드백을 썼나 ③ 왜 생각이 바뀌었나 ④ 아직 모르는 것은 무엇인가. 이 네 가지를 1분에 말할 수 있으면 그 경험은 내 것이에요. 서류 기반 면접은 학생부에 적힌 행동(선택했다·비교했다·수정했다·협력했다)을 근거와 함께 다시 설명하는 시험이에요.</div></div>
  <div class="panel-c" style="background:var(--surface);box-shadow:none"><h3>모의 면접은 선생님과</h3><p style="margin:0;color:var(--ink-2);font-size:14.5px">센터와 학교에서 실제 면접처럼 연습하고 피드백을 받을 수 있어요. AI 연습은 혼자 말해 보는 준비 단계예요.</p><button class="btn btn--primary btn--pill" style="align-self:flex-start" href="counsel.html#book">모의 면접 신청</button></div></div>`;}
/* ── AI 면접 연습 (자기 점검형 · 점수 없음) ── */
let iv={set:0,q:0,phase:'ready',sec:0,t:null,ans:''};
function renderAI(){const T=IVTYPES[iv.set],q=T[2][iv.q];
  $('aiTypes').innerHTML=IVTYPES.map((t,i)=>`<button class="fchip${iv.set===i?' is-on':''}" data-aiset="${i}">${t[0]}</button>`).join('');
  if(iv.phase==='ready')$('aiBody').innerHTML=`<div class="aistage"><div class="aiq"><small>질문 ${iv.q+1} / ${T[2].length}</small><h3>${q}</h3></div><p style="color:var(--ink-2);margin:0">준비되면 시작을 누르세요. 1분 동안 답을 말하고(또는 적고), 끝나면 스스로 점검합니다. <b>점수는 매기지 않아요.</b></p><button class="btn btn--primary btn--pill" data-ai="start" style="padding:14px 28px">▶ 답변 시작 (1분)</button></div>`;
  else if(iv.phase==='answer')$('aiBody').innerHTML=`<div class="aistage"><div class="aiq"><small>질문 ${iv.q+1} / ${T[2].length}</small><h3>${q}</h3></div><div class="timer"><b id="aiSec">${60-iv.sec}</b><span>초 남음</span><div class="score__t" style="width:200px"><div class="score__f" id="aiBar" style="width:${iv.sec/60*100}%"></div></div></div><textarea class="memo" id="aiAns" placeholder="말로 연습하면서 핵심만 적어 두어도 좋아요 (선택)" style="min-height:120px">${iv.ans}</textarea><div style="display:flex;gap:8px"><button class="btn btn--primary btn--pill" data-ai="stop">답변 마치기</button><button class="btn btn--ghost btn--pill" data-ai="reset">처음부터</button></div></div>`;
  else{const ans=iv.ans.trim(),len=ans.length,kw=['계기','어려','해결','배운','연결','학과','이유','예를'].filter(k=>ans.includes(k));
    $('aiBody').innerHTML=`<div class="aistage"><div class="aiq"><small>질문 ${iv.q+1} / ${T[2].length} · 답변 ${iv.sec}초</small><h3>${q}</h3></div>
    <div class="panel-c" style="border:1px solid var(--line);box-shadow:none;width:100%"><h3>스스로 점검해 보세요</h3><div class="reclist">${['결론(답)을 먼저 말했나요?','구체적인 경험이나 예를 들었나요?','지원 학과·진로와 연결했나요?','1분 안에 마쳤나요?'].map((x,i)=>`<label class="cbx" style="min-width:0"><input type="checkbox" data-aick="${i}"><span>${x}</span></label>`).join('')}</div>
    ${len?`<p class="hint" style="margin:0">적은 답변 ${len}자${kw.length?` · 이런 표현이 들어 있어요: ${kw.map(k=>`<b>${k}</b>`).join(', ')}`:' · 계기·어려움·해결·배운 점 같은 흐름이 보이면 더 좋아요'} · <b>이 안내는 글자 확인일 뿐 평가가 아니에요</b></p>`:'<p class="hint" style="margin:0">말로만 연습했어요. 녹음해서 다시 들어보는 것도 좋은 방법이에요</p>'}</div>
    <div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn btn--primary btn--pill" data-ai="next">${iv.q+1<T[2].length?'다음 질문 →':'이 유형 끝 · 처음으로'}</button><button class="btn btn--ghost btn--pill" data-ai="retry">같은 질문 다시</button><button class="btn btn--ghost btn--pill" data-ai="save">연습 기록 저장</button></div></div>`;}
  $('aiLog').innerHTML=(P.interview||[]).length?`<h3 class="lib__h">연습 기록 (${P.interview.length})</h3><ul class="reading">${P.interview.slice(-5).reverse().map(r=>`<li><b>${r.d} · ${IVTYPES[r.set][0]}</b>${r.q} · ${r.sec}초 · 자기 점검 ${r.ok}/4</li>`).join('')}</ul><p class="hint">기록은 모의 면접 신청 시 선생님께 전달할 수 있어요</p>`:'';}
function aiTick(){iv.sec++;const s=$('aiSec'),b=$('aiBar');if(s)s.textContent=60-iv.sec;if(b)b.style.width=iv.sec/60*100+'%';if(iv.sec>=60)aiStop();}
function aiStop(){clearInterval(iv.t);iv.ans=$('aiAns')?$('aiAns').value:iv.ans;iv.phase='review';renderAI();}
/* ── 대학별고사 자료 ── */
const EXAMS=[['논술','한강대 2026 논술 기출 및 해설','한강대','인문·자연','2026.01'],['논술','논술 전형 준비 가이드 (센터)','서울진로진학정보센터','공통','2026.05'],['면접','서울미래대 2026 면접 기출 문항','서울미래대','학생부종합','2026.02'],['면접','서울교대 교직 적성·인성 면접 안내','서울교대','교직','2026.03'],['면접','학생부 기반 면접 예상 질문 워크시트','쎈(SEN)진학','공통','2026.09'],['실기','서울디자인예술대 실기 출제 경향','서울디자인예술대','디자인','2026.04'],['공통','선행학습 영향평가 결과보고서 모음 (대학별 기출 공개)','각 대학','공통','2026.03']];
let exK='전체';
function renderExam(){$('exTabs').innerHTML=['전체','논술','면접','실기','공통'].map(k=>`<button class="fchip${exK===k?' is-on':''}" data-exk="${k}">${k}</button>`).join('');
  $('exList').innerHTML=EXAMS.filter(e=>exK==='전체'||e[0]===exK).map(e=>`<li class="row"><span class="row__ic">${{'논술':'✍️','면접':'🗣️','실기':'🎨','공통':'📄'}[e[0]]}</span><button class="row__main" data-toast="자료를 내려받습니다 · ${e[1]}"><b>${e[1]}</b><span>${e[0]} · ${e[2]} · ${e[3]} · ${e[4]}</span></button><div class="row__files"><button class="file" data-toast="${e[1]}">PDF</button></div></li>`).join('');}
/* ── 탭 ── */
let tab='grades';
const R={grades:renderGrades,record:renderRecord,analysis:renderAnalysis,convert:renderConvert,result:renderResult,possible:renderPossible,cmp:renderCmp,plan:renderPlan,check:renderCheck,interview:renderInterview,aiint:renderAI,exam:renderExam};
function rerender(){const g=GROUP[tab];
  $('ptabs').innerHTML=Object.keys(L3).filter(k=>GROUP[k]===g).map(k=>`<a class="ptab${k===tab?' is-on':''}" href="#${k}">${L3[k]}</a>`).join('');
  $('crumbL2').textContent=L2[g];$('crumbL3').textContent=L3[tab];$('h1').textContent=L2[g];
  $('hdesc').textContent={r:'성적과 학교생활을 간단히 정리해 두는 곳입니다. 세부 분석은 상담에서 선생님이 내가 동의한 자료로 함께 봅니다.',c:'대학별 환산과 입시결과를 이해하는 곳입니다. 합격 가능성 판정은 하지 않고, 상담에서 정리한 참고 범위만 보여드립니다.',p:'관심 전형을 비교해 수시 6장·정시 3장 계획을 세우고, 살펴볼 점을 정리해 상담으로 가져갑니다.',i:'면접 유형을 이해하고 혼자 연습해 본 뒤, 모의 면접은 선생님과 합니다.'}[g];
  const gated=!OPEN.has(tab)&&!A.logged();
  $('gateBox').innerHTML=gated?A.gate('🔒',L3[tab]+'은(는) 로그인 후 이용할 수 있어요','내 성적·관심 전형을 바탕으로 하는 기능이라 본인 확인이 필요합니다. 입력한 내용은 상담 사전자료로만 쓰이고, 공유 범위는 내가 정합니다.'):'';
  document.querySelectorAll('.pane').forEach(p=>p.classList.toggle('is-on',!gated&&p.id==='pane-'+tab));
  if(!gated)R[tab]();}
function setTab(){tab=(location.hash||'#grades').slice(1);if(!L3[tab])tab='grades';document.querySelectorAll('#lnb a').forEach(a=>a.classList.toggle('is-cur',a.getAttribute('href')==='strategy.html#'+tab));document.title=L3[tab]+' | 서울 진로진학 통합플랫폼';rerender();}
$('lnb').dataset.current=L3[(location.hash||'#grades').slice(1)]||L3.grades;
addEventListener('hashchange',()=>{if(dirty){showToast('저장하지 않은 성적 변경이 있어요 · 내신·모의고사에서 저장해 주세요');}setTab();scrollTo({top:document.querySelector('.ptabs').offsetTop-90,behavior:'smooth'});});
document.addEventListener('sen-auth',rerender);
function addPlan(id){const a=adm(id);if(a.season==='수시'){if(P.plan.susi.includes(id)){P.plan.susi=P.plan.susi.filter(x=>x!==id);save();showToast('지원계획에서 뺐어요');}else if(P.plan.susi.length>=6)showToast('수시는 6장까지예요');else{P.plan.susi.push(id);save();showToast('수시 지원계획에 담았어요');}}else{const g=a.group==='추가'?'다':a.group;if(P.plan.jeongsi[g]===id){P.plan.jeongsi[g]=null;save();showToast('지원계획에서 뺐어요');}else{P.plan.jeongsi[g]=id;save();showToast(`정시 ${g}군에 담았어요${P.plan.jeongsi[g]?'':''}`);}}rerender();}
document.addEventListener('click',e=>{const c=x=>e.target.closest(x);let b;
  if(b=c('[data-gt]')){gTab=b.dataset.gt;renderGrades();return;}
  if(b=c('[data-gact]')){if(b.dataset.gact==='save'){P.grades=D.grades;P.mock=D.mock;P.savedAt='2026.10.02 '+new Date().toTimeString().slice(0,5);save();dirty=false;D=null;showToast('성적을 저장했어요 · 분석과 상담 사전자료에 반영됩니다');}else{D=null;dirty=false;showToast('변경을 취소했어요');}renderGrades();return;}
  if(b=c('[data-req]')){P.consult='req';save();showToast('환산 요청과 함께 상담을 신청했어요 · 입력한 성적·관심 전형이 전달됩니다');location.hash='#possible';return;}
  if(b=c('[data-consult]')){P.consult=b.dataset.consult;save();showToast(b.dataset.consult==='req'?'상담을 신청했어요':'(목업) 상담 완료 상태로 바꿨어요');renderPossible();return;}
  if(b=c('[data-addplan]')){e.stopPropagation();addPlan(b.dataset.addplan);return;}
  if(b=c('[data-rmplan]')){e.stopPropagation();const id=b.dataset.rmplan;P.plan.susi=P.plan.susi.filter(x=>x!==id);Object.keys(P.plan.jeongsi).forEach(g=>{if(P.plan.jeongsi[g]===id)P.plan.jeongsi[g]=null;});save();renderPlan();return;}
  if(b=c('[data-slot]')){location.hash='#cmp';return;}
  if(c('#plSend')){P.memoTeacher=$('plMemo').value;save();showToast('지원계획을 선생님께 보냈어요 · 상담에서 함께 봅니다');return;}
  if(b=c('[data-ivset]')){iv={set:+b.dataset.ivset,q:0,phase:'ready',sec:0,t:null,ans:''};return;}
  if(b=c('[data-aiset]')){clearInterval(iv.t);iv={set:+b.dataset.aiset,q:0,phase:'ready',sec:0,t:null,ans:''};renderAI();return;}
  if(b=c('[data-ai]')){const k=b.dataset.ai;if(k==='start'){iv.phase='answer';iv.sec=0;iv.ans='';renderAI();iv.t=setInterval(aiTick,1000);}else if(k==='stop')aiStop();else if(k==='reset'||k==='retry'){clearInterval(iv.t);iv.phase='ready';iv.sec=0;iv.ans='';renderAI();}else if(k==='next'){iv.q=(iv.q+1)%IVTYPES[iv.set][2].length;iv.phase='ready';iv.sec=0;iv.ans='';renderAI();}else if(k==='save'){const ok=document.querySelectorAll('[data-aick]:checked').length;(P.interview=P.interview||[]).push({d:'2026.10.02',set:iv.set,q:IVTYPES[iv.set][2][iv.q],sec:iv.sec,ok});save();showToast('연습 기록을 저장했어요');renderAI();}return;}
  if(b=c('[data-exk]')){exK=b.dataset.exk;renderExam();return;}
  if(b=c('[data-adm]')){if(c('[data-addplan],[data-rmplan]'))return;const a=adm(b.dataset.adm);if(a)location.href='univ.html?open='+a.id+'#susi';return;}
});
document.addEventListener('change',e=>{const g=e.target.closest('[data-g]');if(g){ensureD();const k=g.dataset.g,sj=g.dataset.s,v=+g.value||'';const tgt=k.includes('-')&&k.length<=3?D.grades:D.mock;(tgt[k]=tgt[k]||{})[sj]=v;dirty=true;renderGrades();return;}
  const d2=e.target.closest('[data-d2]');if(d2){const [g2,k2]=d2.dataset.d2.split(':');(P.detail=P.detail||{});(P.detail[g2]=P.detail[g2]||{})[k2]=e.target.value;save();return;}
  const mx2=e.target.closest('[data-mx]');if(mx2){const [id2,k2]=mx2.dataset.mx.split(':');(P.mx=P.mx||{});(P.mx[id2]=P.mx[id2]||{})[k2]=e.target.value;save();renderPlan();return;}
  const r=e.target.closest('[data-rec]');if(r){P.rec[r.dataset.rec]=e.target.checked;save();renderRecord();return;}
  const ck=e.target.closest('[data-ckl]');if(ck){P.ckl=P.ckl||[];const i=+ck.dataset.ckl;e.target.checked?P.ckl.push(i):P.ckl=P.ckl.filter(x=>x!==i);save();return;}});
setTab();
})();
